### ISSUE TITLE
Strange behavior in `sfr_avg()` method when passing float vs. array as input tage

### ISSUE THREAD

**Issue by rrgupta** [dfm/python-fsps#103]
https://github.com/dfm/python-fsps/blob/8361d601048ca3873ee32a4559bb52306f388c7b/fsps/fsps.py#L1051
Hi @bd-j,
When playing with the `sfr_avg` method I stumbled across some weird behavior. My understanding is that the method ought to work the same when given an input `tage` that is either a scalar (e.g., float) or an iterable (e.g., numpy array). However, I'm finding that when I pass `tage` to `sfr_avg` as a numpy array I get different output values than if I individually pass each element of the array to `sfr_avg` as floats. For some models, I get very different answers that can disagree by more than a factor of 2! A clue to what's going on might be that only the last elements of the arrays agree (i.e., the 2 methods agree only for the final age element). Please see the example below (Python notebook copy-pasted as Markdown).

I can't figure out where in the code the problem lies but it might be something subtle to do with Python's dynamical typing or something going on under the hood in numpy. Or I could just be doing something wrong, but I don't see how.

Thanks,
Ravi

```python
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import fsps
```

```python
csp = fsps.StellarPopulation(sfh=4, tau=4, sf_start=7)
ages = np.arange(10, 13, step=0.1)
```

```python
# First compute sfr given input numpy array of age
array_sfr = csp.sfr_avg(ages)

loop_sfr = []
# Now compute same sfr by looping over the age array
for a in ages:
    loop_sfr.append(csp.sfr_avg(a)[0])
loop_sfr = np.array(loop_sfr)
```

```python
print array_sfr
print loop_sfr
```

    [  2.03295762e-10   2.04998079e-10   2.06492407e-10   2.07787977e-10
       2.08893694e-10   2.09818143e-10   2.10569601e-10   2.11156046e-10
       2.11585170e-10   2.11864382e-10   2.12000824e-10   2.12001376e-10
       2.11872665e-10   2.11621074e-10   2.11252749e-10   2.10773607e-10
       2.10189346e-10   2.09505448e-10   2.08727189e-10   2.07859647e-10
       2.06907703e-10   2.05876056e-10   2.04769220e-10   2.03591538e-10
       2.02347182e-10   2.01040164e-10   1.99674336e-10   1.98253398e-10
       1.96780904e-10   1.95260268e-10]
    [  5.08680710e-10   4.87913171e-10   4.68447042e-10   4.50165962e-10
       4.32967043e-10   4.16758973e-10   4.01460438e-10   3.86998782e-10
       3.73308894e-10   3.60332247e-10   3.48016086e-10   3.36312737e-10
       3.25179010e-10   3.14575677e-10   3.04467038e-10   2.94820523e-10
       2.85606364e-10   2.76797295e-10   2.68368297e-10   2.60296370e-10
       2.52560334e-10   2.45140651e-10   2.38019269e-10   2.31179486e-10
       2.24605823e-10   2.18283915e-10   2.12200411e-10   2.06342888e-10
       2.00699774e-10   1.95260268e-10]

```python
fig = plt.figure(figsize=(8,4))
ax1 = fig.add_subplot(121)
ax1.scatter(ages, np.log10(array_sfr), label='sfr from array')
ax1.scatter(ages, np.log10(loop_sfr), label='sfr from float')
ax1.set_xlabel('Age')
ax1.set_ylabel('log SFR')
ax1.legend()

ax2 = fig.add_subplot(122)
ax2.scatter(np.log10(array_sfr), np.log10(loop_sfr))
ax2.set_xlabel('log SFR from array')
ax2.set_ylabel('log SFR from float')
fig.tight_layout()
```

![float_v_array](https://user-images.githubusercontent.com/7378075/44304076-71d95580-a306-11e8-83bb-e986cda8f2b6.png)

**Comment by bd-j** [comment]
So I think I have fixes for this and the issues in #69.  It comes down to always using the value of `params["tage"]` as the maximum age (or using the maximum isochrone age if `params["tage"] = 0`).
The main remaining questions are whether it's important that the shape of the output be the same as the input times, and what to report for times outside the range `(sf_start + dt, tage)`.  I also fixed the burst issue. If this looks ok I will commit and push.

```python
def sfr_avg_new(self, times=None, dt=0.1):
    """
    The average SFR between ``time``-``dt`` and ``time``, given the
    SFH parameters, for ``sfh=1`` or ``sfh=4``.  Like SFHSTAT in FSPS.
    Requires scipy, as it uses gamma functions.

    :param times: (default, None)
        The ages (in Gyr) at which the average SFR over the last ``dt`` is
        desired.  if ``None``, uses the current value of the ``tage`` in
        the parameter set. Scalar or iterable.

    :param dt: (default: 0.1)
        The time interval over which the recent SFR is averaged, in Gyr.
        defaults to 100 Myr (i.e. sfr8).

    :returns sfr_avg:
        The SFR at ``tage`` averaged over the last ``dt`` Gyr, in units of
        solar masses per year, such that :math:`1 M_\odot` formed by `tage`.  Same
        shape as ``times``
    """
    from scipy.special import gammainc
    assert self.params['sf_trunc'] <= 0, "sfr_avg not supported for sf_trunc > 0"
    if self.params['sfh'] == 1:
        power = 1
    elif self.params['sfh'] == 4:
        power = 2
    else:
        raise ValueError("sfr_avg not supported for this SFH type.")

    tau, sf_start = self.params['tau'], self.params['sf_start']
    if self.params['tage'] <= 0:
        tage = 10**(np.max(self.ssp_ages) - 9)
    else:
        tage = np.array(self.params['tage'])

    if times is None:
        times = tage
    else:
        times = np.array(times)

    tb = (self.params['tburst'] - sf_start) / tau
    tmax = (tage - sf_start) / tau
    normalized_times = (np.array([times, times - dt]).T - sf_start) / tau

    tau_mass_frac = gammainc(power, normalized_times) / gammainc(power, tmax)
    burst_in_past = (tb <= normalized_times)
    mass = (tau_mass_frac * (1 - self.params['const'] - (tb < tmax) * self.params['fburst']) +
            self.params['const'] * normalized_times / tmax +
            burst_in_past * self.params['fburst'])

    avsfr = (mass[..., 0] - mass[..., 1]) / dt / 1e9  # Msun/yr

    # These lines change behavior when you request sfrs outside the range (sf_start + dt, tage)
    #avsfr[times > tage] = np.nan  # does not work for scalars
    avsfr *= times <= tage
    #avsfr[np.isfinite(avsfr)] = 0.0 # does not work for scalars

    return np.clip(avsfr, 0, np.inf)

```

**Comment by rrgupta** [comment]
Thanks for looking into this. I think ultimately what users would want (at least users like myself) is something most analogous to the traditionally used sSFR averaged over `dt` (i.e., solar masses formed per year over the past `dt` years divided by the current stellar mass). 

Perhaps the way to obtain this is for each `t` in `times`, normalize the SFH(t) such that 1 Msun is formed from `sf_start` to `t`. (I believe this is how the FSPS masses are normalized, right? That is, for a given `tage` value, `sp.formed_mass` always equals 1.0 and `sp.stellar_mass` gives the fraction of `sp.formed_mass` that is still locked up in stars + remnants.) This would given you the SFR per unit formed mass. Then one can get the traditional sSFR by looping over `times`, setting `self.params['tage']` to the current element of `times` and doing `sp.sfr_avg_new(t)/sp.stellar_mass`. Am I thinking about this right?

Re: times outside the range `(sf_start + dt, tage)`, maybe the way to deal with this is to treat `tage` as just any other age value. If the SFH being integrated is normalized to each input age value (whether that age is `tage`, some other float, or some array of ages) then the function will always behave consistently. Since the SFHs are defined from 0 to inf then I think it's fair to return `avsfr = 0` for any times before `sf_start` since star formation has not yet begun and treat any other age value that is > `sf_start` in the same way. Basically, make it so there is nothing special about `self.params['tage']` from the point of view of `sfr_avg_new`.

Now, maybe this normalization scheme is not useful for people wanting to see the SFR evolve over time. So maybe there could be a switch where the user could either specify normalization to each age element as I suggested above *or* set the normalization to be such that 1 Msun is formed over the entire SFH.

Re: your new formulation of `sfr_avg_new`, I don't quite understand what's happening in the `mass` equation. Why is the term `(tb < tmax) * self.params['fburst']` not `burst_in_past * self.params['fburst']` like it is in the final term?

**Comment by bd-j** [comment]
Hi @rrgupta, thanks for your comments.  What you are suggesting (sfr/current_mass for arbitrary ages; tage just like any other age value) is much more like what the code was like before, when implemented as a loop (i.e., `loop_sfr` above).  Unfortunately, there are a number of complications that arise in this formulation:

First, obtaining the current stellar mass for arbitrary age is not trivial. As the code is set up, the spectrum would actually have to be synthesized for every element of `times` in your formulation.

Second, whether the burst is entirely ignored or not in the FSPS calculations depends on the value of `tage`, so it's a little tricky to completely ignore `tage` and be sure the calculated SFRs correspond to the calculated spectrum.  Also what you describe would give something like the `loop_sfr` above, which I'm pretty sure would be confusing to a number of users for a function that purports to give the SFR (at a given time) associated with the computed spectrum and SFH parameters.

I think there is a desire in many cases to get the actual evolution of the SFR that led to the computed spectrum, which is the formulation given in `sfr_avg_new()`. This is especially true for `tage=0` But as you say, you could also get what you describe by doing
```python
for i, t in enumerate(times):
    sp.params["tage"] = t
    ssfr[i] = sp.sfr_avg_new() / sp.stellar_mass
```
*outside* of `sfr_avg`. It seems a bit clearer to me to do it this way.  It is also more flexible, since you can now either change `params["tage"]` or `times` depending on what exactly you want to do.

Re `(tb < tmax)`, this is because, to get the SFR evolution leading to the computed spectrum, the total mass contribution of the tau component must be reduced if the burst is *ever* added to the spectrum, which it is if tb < tmax.  Here's a test version you can play with to see what's going on; just move `"tburst"`  before and after tage:

```python
def sfr_avg(times=None, dt=0.1, ssp_ages=[10.15], **params):
    """
    The average SFR between ``time``-``dt`` and ``time``, given the
    SFH parameters, for ``sfh=1`` or ``sfh=4``.  Like SFHSTAT in FSPS.
    Requires scipy, as it uses gamma functions.

    :param times: (default, None)
        The ages (in Gyr) at which the average SFR over the last ``dt`` is
        desired.  if ``None``, uses the current value of the ``tage`` in
        the parameter set. Scalar or iterable.

    :param dt: (default: 0.1)
        The time interval over which the recent SFR is averaged, in Gyr.
        defaults to 100 Myr (i.e. sfr8).

    :returns sfr_avg:
        The SFR at ``tage`` averaged over the last ``dt`` Gyr, in units of
        solar masses per year.  Same shape as ``times``
    """
    from scipy.special import gammainc
    assert params['sf_trunc'] <= 0, "sfr_avg not supported for sf_trunc > 0"
    if params['sfh'] == 1:
        power = 1
    elif params['sfh'] == 4:
        power = 2
    else:
        raise ValueError("sfr_avg not supported for this SFH type.")

    tau, sf_start = params['tau'], params['sf_start']
    if params['tage'] <= 0:
        tage = 10**(np.max(ssp_ages) - 9)
    else:
        tage = np.array(params['tage'])

    if times is None:
        times = tage
    else:
        times = np.array(times)

    tb = (params['tburst'] - sf_start) / tau
    tmax = (tage - sf_start) / tau
    normalized_times = (np.array([times, times - dt]).T - sf_start) / tau

    tau_mass_frac = gammainc(power, normalized_times) / gammainc(power, tmax)
    burst_in_past = (tb <= normalized_times)
    mass = (tau_mass_frac * (1 - params['const'] - (tb < tmax) * params['fburst']) +
            params['const'] * normalized_times / tmax +
            burst_in_past * params['fburst'])

    avsfr = (mass[..., 0] - mass[..., 1]) / dt / 1e9  # Msun/yr

    # These lines change behavior when you request sfrs outside the range (sf_start + dt, tage)
    #avsfr[times > tage] = np.nan  # does not work for scalars
    avsfr *= times <= tage
    #avsfr[np.isfinite(avsfr)] = 0.0 # does not work for scalars

    return np.clip(avsfr, 0, np.inf)

if __name__ == "__main__":

    params = {"sfh": 4,
              "tau": 3.0,
              "sf_start": 1.0,
              "sf_trunc": 0,
              "tage": 13.7,
              "tburst": 5.0,
              "fburst": 0.0,
              "const": 0.0,
              }
    times = np.linspace(0.1, 15.7, 1000)
    params["fburst"] = 0.2
    params["tburst"] = 13.9
    sfr = sfr_avg(times, **params)

    import matplotlib.pyplot as pl
    fig, ax = pl.subplots()
    ax.plot(times, sfr)

```

**Comment by bd-j** [comment]
PS, it's probably key to note that in the loop I gave above to get `ssfr`, every time you change `params["tage"]` this causes a call to `sp.stellar_mass` to internally **recompute** both the spectrum and the current mass.  If you don't change `params["tage"]` or any other parameter then the code does not know to recompute anything.

**Comment by rrgupta** [comment]
Hi @bd-j,
OK, I think I understand now, and I agree with you. The way I am using FSPS, I am looping over an array of ages and recomputing model spectra and masses at each time step anyways. So as long as I can continue doing this and then also compute the traditional sSFR as `ssfr[i] = sp.sfr_avg_new() / sp.stellar_mass` inside that loop then I am happy! Thanks!

**Comment by bd-j** [comment]
The `sfr_avg()` method was altered as described above by #107, closing this issue.
