### ISSUE TITLE
Installing via pip note

### ISSUE THREAD

**Issue by astrophysaxist** [dfm/python-fsps#104]
Hi, this is more of a note than an issue. I just grabbed python-fsps using pip, and I ran into an ImportError: Permission denied message when I went to import fsps for the first time.

Turns out pip seems to occasionally set the umask permissions restrictively. I was able to import successfully, though after running:
```
chmod -R a+rx /usr/lib/python2.7/site-packages/fsps*
```
Best,
Greg

**Comment by bd-j** [comment]
Thanks for the note (and the fix!).  The pip version is also rather out of date, we recommend installing the development version if at all possible.

http://dfm.io/python-fsps/current/installation/#installing-development-version

**Comment by astrophysaxist** [comment]
Thanks for letting me know! I was suspicious that the pip version was out of date because the example was not working. Even with version 0.3.0 though I'm getting:

```python
>>> import fsps
>>> fsps.__version__
'0.3.0'
>>> sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1,sfh=0,logzsol=0.0,dust_type=2,dust2=0.2)
>>> sp.libraries()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object is not callable
```
But maybe the example is out of date here:
http://dfm.io/python-fsps/current/stellarpop_api/#example

**Comment by bd-j** [comment]
yes the example as given is wrong and I haven't gotten around to rebuilding the pages (see #82, #87)

**Comment by astrophysaxist** [comment]
Cool beans, thanks for the links!
