### ISSUE TITLE
Smoothing and Resolution

### ISSUE THREAD

**Issue by gannonjs** [dfm/python-fsps#113]
Hello,

I am interested in creating a high resolution spectra with a velocity dispersion of about 25 km/s. Using the sigma_smooth parameter I am finding that it seems to do very little when set to anything below ~55 km/s [which is about the resolution of the MILES spectral library the code is using]. Is the code limited by the spectral library it uses [And hence I cannot create something with greater resolution] or should I be able to create the narrower emission features I seek?

Thanks
Jonah

**Comment by bd-j** [comment]
yes, the output resolution is limited by the input spectral library, and MILES is the highest resolution library currently available in FSPS.
