### ISSUE TITLE
py-fsps documentation says compiling FSPS with -fPIC is not necessary using gfortran when it may be

### ISSUE THREAD

**Issue by spencerscott917** [dfm/python-fsps#116]
I recently tried to install python-fsps on my desktop, running Ubuntu 18.04, with FSPS compiled using gfortran 9.2.0. I had a problem installing python-fsps at first, and upon reading the documentation, saw that issues can sometimes be resolved by recompiling FSPS using the -fPIC flags. The documentation states that this is for Intel compilers, and shouldn't apply to gfortran. However, using gfortran and recompiling using these flags, installation was successful.

**Comment by dfm** [comment]
#136 removes this discussion from the docs because all the flags should now be handled automatically by Python.
