### ISSUE TITLE
sp.emline_luminosity units

### ISSUE THREAD

**Issue by dnarayanan** [dfm/python-fsps#117]
hey! very simple question - if i try something like the example on the docs page:

```
import fsps
sp = fsps.StellarPopulation(zcontinuous=1,add_neb_emission=1)
sp.params['logzsol'] = -1.0
sp.params['gas_logz'] = -1.0
sp.params['gas_logu'] = -2.5
wave, spec = sp.get_spectrum(tage=0.001)

print(sp.emline_luminosity)
```

what are the default units of the line luminosity?  and, is this integrated over the entire line profile?

**Comment by dnarayanan** [comment]
just kidding - answered in `fsps.py`:

```
    @property
    def emline_luminosity(self):
        """emission line luminosities, in :math:`L_\odot`. shape=(ne)
        """
        return self._stat(6)
```

**Comment by dnarayanan** [comment]
actually re-opening to check...any chance these units are actually Lsun/AA ?

**Comment by bd-j** [comment]
I don't think so.  They should be Lsun per solar mass formed for SFH=0, 1, 4.  For SFH=3 they should just be Lsun.

**Comment by dnarayanan** [comment]
ah okay thanks!
