### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by bd-j** [dfm/python-fsps#119]
@dfm Should this get moved to readthedocs or some such?

**Comment by dfm** [comment]
The new URL is http://dfm.io/python-fsps, but yes readthedocs would be better! I can take a peak at how hard that would be to get up and running tomorrow.

**Comment by dfm** [comment]
I decided that I didn't want to figure out how to build FSPS on readthedocs so I updated the travis script to build the docs every time you push to master. However, it looks like there's a discrepancy between `fsps.__version__` (0.3.0) and the docs version (0.3.1). If you update the fsps version, the docs will update accordingly!
