### ISSUE TITLE
Version checking raises error on import

### ISSUE THREAD

**Issue by imariasantos** [dfm/python-fsps#122]
I cloned fsps and python-fsps from github and installed them yesterday. Therefore, I am using git version control and I assume that I have the most up to date version. Yet using `import fsps` in a python script raises
`ImportError: Your FSPS version does not seem to be under git version control. FSPS is available on github at https://github.com/cconroy20/fsps and should be cloned from there`

I had to edit out the version check from `fsps/__init__.py` to be able to import library.

**Comment by bd-j** [comment]
The version check is now removed by the use of FSPS as a submodule.
