### ISSUE TITLE
What is \AA in docstrings?

### ISSUE THREAD

**Issue by imariasantos** [dfm/python-fsps#123]
From the docstrings, 
```
:math:`\AA`
``` 
renders as a red "\AA" in the documentation in both Firefox and Chromium. What unit is this supposed to be?

**Comment by jrleja** [comment]
This is the LaTeX command for Angstroms.

**Comment by imariasantos** [comment]
It doesn't render properly in the online documentation.

**Comment by dfm** [comment]
"Fixed" in #136
