### ISSUE TITLE
Formed mass appears to not work with a tabular star formation history

### ISSUE THREAD

**Issue by davidjsetton** [dfm/python-fsps#125]
This seems relatively minor, but after generating a stellar population with a tabulated star formation history, I've noticed that sp.stellar_mass returns a value that makes sense for the total stellar mass remaining, but sp.formed_mass returns 1.0 instead of the actual value of the total mass formed.

**Comment by bd-j** [comment]
this is an issue with fsps itself; using `np.trapz(sfr, age)` is a reasonable workaround until this is fixed in the fortran.  Note the `stellar_mass` attribute should still be correct.

**Comment by bd-j** [comment]
fixed by cconroy20/fsps#58
