### ISSUE TITLE
Calculating Mass-to-light ratios in FSPS

### ISSUE THREAD

**Issue by mkurzner** [dfm/python-fsps#128]
Hi there,

I recently started using FSPS with the aim of calculating M/L_V ratios for various SFH. I was wondering if I should be taking an approach similar to what I am doing below or if there is something that I am missing built into FSPS that I am missing that will make it easier to calculate these ratios. For example in this code I attempted to calculate the V band luminosity for a SSP at 100 different times to see how the M/L_V ratio evolves. I am not sure if I am on the right track with this so any help on this would be greatly appreciated. 

Thank you very much!
Max

```
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1, sfh=0, logzsol=0.0, dust_type=0, dust_index= 0, dust1_index=0,  imf_type= 2, add_stellar_remnants=True)


lower_bound=5000 # lower bound of V band in \AA
upper_bound=7000 #upper bound of V band in \AA

mags=sp.get_mags(bands='v') #Using Johnson V Band
tage_arr=np.linspace(0.01,13.7,100)
wave_v=np.zeros(0)
spec_v=np.zeros(0)
L_arr=np.zeros(0)
m_arr=np.zeros(0)
for t in range(len(tage_arr)):
    wave, spec = sp.get_spectrum(tage=tage_arr[t],peraa= True)
    m=sp.stellar_mass
    m_arr=np.append(m_arr,[m])
    for i in range(len(wave)):
        if lower_bound < wave[i] < upper_bound:   
            wave_v=np.append(wave_v,[wave[i]])
            spec_v=np.append(spec_v,[spec[i]])
    L_arr=np.append(L_arr,[np.trapz(spec_v)])
  
```

**Comment by bd-j** [comment]
It depends a little on how you're definig mass/light ratio, but I think you can get the V-band luminosity more directly and accurately from the magnitude calculated with get_mags

```python
mag = np.zeros_like(tage_arr)
mass = np.zeros_like(tage_arr)
for i, tage in enumerate(tage_arr):
    mag[i] = sp.get_mags(tage=tage, bands=["v"])
    mass[i] = sp.stellar_mass

M_v_sol = 4.83
lum = 10**(0.4 * (M_v_sol - mag))
mass2light = mass / lum
```

**Comment by mkurzner** [comment]
Hi @bd-j the aim was to define mass/light ratio as the total mass of stars and stellar remnants divided by the V-band luminosity. I believe that this method that you suggested is more accurate as when compared to my previous attempts I get mass/light ratios about an order of magnitude smaller, much more in line with what I have seen in the literature. Thank you very much for your help. I am puzzled as to why my values for my first method are so off but I will go back to it and try and get the values to agree.

**Comment by bd-j** [comment]
@mkurzner note that in your formulation the luminosity depends sensitively on the width of the band.  What I think is commonly done is to estimate the average luminosity *density* (e.g. Lsol/Hz) within the band and compare that to the luminosity density of the sun.  Magnitudes are fundamentally a measure of flux or luminosity density, so they are useful for this.  The method I outlined also naturally takes into account the variations in the V band transmission with wavelength.
