### ISSUE TITLE
Bottom Heavy IMFs Used in FSPS and Gas Recycling

### ISSUE THREAD

**Issue by mkurzner** [dfm/python-fsps#131]
Hi,

I wanted to follow up on my previous question on M/L ratios with varying IMFs by asking if it is possible to generate the functional forms of the Bottom Heavy IMFs as specified in van Dokkum, Conroy et al. 2017.  I have been using this IMF as a user specified IMF in FSPS with the following logarithmic slopes:

 0.08 M<sub>Sun</sub> < 2.97 M < 0.5 M<sub>Sun</sub>
2.13  0.5 M<sub>Sun</sub> < M < 1 M<sub>Sun</sub> 
and 2.3 otherwise 

I am getting discontinuities when attempting to plot these IMFs which I am using in the M/L calculations and am not sure if I am either missing a normalization factor or made an error when converting to dN/dM from dN/dlogM. From the documentation in sps_vars.f90 and imf.f90 I believe the IMFs generated by FSPS are in terms of dN/dM but I want to be completely sure before trying to make IMF plots of my own. 

Additionally I was wondering what the defaults for Gas Recycling in the ISM are in FSPS and if this is a parameter that can be controlled when generating stellar populations using FSPS. Thank you very much for your help!

**Comment by cconroy20** [comment]
if you want to set the PL slopes in the intervals 0.08-0.5, 0.5-1.0, and 1.0-100, then you can use the parameters imf1, imf2, and imf3.  See page 7 of the manual, under "basic parameters"

**Comment by mkurzner** [comment]
Hi Dr. Conroy,

Thank you very much for your reply to my question. I realize now that my question was poorly worded. I have been using an IMF with PL slopes specified with imf1,imf2 and imf3  but was wondering if there was a difference to the functional form of the Bottom Heavy IMF with x<sub>1</sub> = 2.97 and if it is possible to generate the IMF as used by FSPS as an output.  IWhen I plot the IMF shown here I am getting a rather sharp discontinuity at 0.08 M <sub> Sun </sub>.  Is there something that I am missing that ensures continuity or have I made another mistake such as not normalizing the IMF correctly. The M/L<sub> V </sub> ratios that I am calculating with these bottom heavy IMFs make sense so I wanted to check that I am able to plot and correctly reproduce the IMFs used to help generate the SSPs. 

![IMFs_81420](https://user-images.githubusercontent.com/27359290/90257832-ab6dca00-de15-11ea-8575-9b65d7bf12ad.png)

Best,
Max

**Comment by cconroy20** [comment]
how are you computing the orange line below?  You need normalizing constants whenever the slope changes.  See L47-54 in imf.f90 in fsps/src

Charlie

**Comment by mkurzner** [comment]
Hi Charlie,

Thank you again for the quick reply. I think I am being too naive in my calculation of the orange line.  I was computing it as simply m<sup> -x<sub>1</sub> </sup> and so forth for the various mass ranges instead of the normalization method used in the Kroupa broken power law. I have gone ahead and made the changes to my IMF calculation and realize my mistake.  Additionally is there an FSPS parameter to control the rate of ISM Gas Recycling as mentioned in work such as Zahid et al. 2017?  I am not sure if FSPS directly handles this or if you need to input the SSPs into a separate model to do so. 

Best,
Max
![](http://localhost:8888/view/Desktop/Tufts/Research/IMFs_81420_Updated.png)
![IMFs_81420_Updated](https://user-images.githubusercontent.com/27359290/90269944-710d2880-de27-11ea-82c4-27785daa4c46.png)

**Comment by cconroy20** [comment]
FSPS keeps track of the initial mass formed and the current mass still in stars, so the subtraction of those two gives you the return mass.  That’s all FSPS tabulates.

Charlie

**Comment by mkurzner** [comment]
Hi Charlie,

That is what I figured after reading over the FSPS documentation but wanted to make sure while I was on the subject of IMFs in FSPS. Thank you again for all your help and I believe that resolves my issue so I can close this issue now.

Max
