### ISSUE TITLE
Running Python-FSPS on Windows 10

### ISSUE THREAD

**Issue by mkurzner** [dfm/python-fsps#132]
Hi there,

I recently tried to get FSPS and Python-FSPS up and running on a Windows PC (I am using Ubuntu 20.04.1 and Windows 10) and ran into issues utilizing Python-FSPS in a Jupyter Notebook in Windows. I was able to install and run FSPS and Python-FSPS without issue in Ubuntu through Windows Subsystem for Linux but was hoping to be able to run it as normal in Jupyter with Anaconda that I have already setup using Jupyter on a Macbook. The specific issue I am getting in Anaconda is that I am able to import fsps into a Jupyter-Notebook but then when I try to run anything it says that fsps has no attributes which leads me to believe that Anaconda is having trouble accessing all of the fsps files. I hope that I am not overlooking something obvious in the documentation about Python-FSPS not being supported on Windows, If this is the case I can attempt to run my scripts completely in a Unix environment on my PC, otherwise please let me know if there is any potential workaround for this.

Thank you!
Max

**Comment by bd-j** [comment]
yes, sorry, we assume a *nix system and have neither tested nor support windows at this time -- see #76

**Comment by mkurzner** [comment]
Hi Ben,

Thank you for linking that to me, I appreciate you clearing that up.

Best,
Max
