### ISSUE TITLE
Publish v0.3 release

### ISSUE THREAD

**Issue by dfm** [dfm/python-fsps#141]
@bd-j: I think we're probably nearly good to go for a v0.3 release after we fix #139 and perhaps #138. I've pushed [a release candidate to PyPI](https://pypi.org/project/fsps/0.3.0rc1/) with binary wheels so you'll find that if you run:

```bash
python -m pip install fsps==0.3.0rc1
```

It should directly install the binary on all platforms and Python 3.6-3.9 - no Fortran compiler needed!

These releases are automatically executed on GitHub actions when we tag a GitHub release. Perhaps I should add some text to the docs about that process?

**Comment by dfm** [comment]
Actually: we might want to make it the v0.4 release since the GitHub version has been 0.3.0 for a while even though this was never released on PyPI?

**Comment by Dh-hgi** [comment]
Hi, 

I have installed FSPS using "python -m pip install fsps==0.3.0rc1"

Now when I am running the code written as

sps = fsps.StellarPopulation(zcontinuous=1)
sps.params['imf_type'] = 0   # Salpeter IMF
sps.params['sfh'] = 1  # Tau model SFH
iso = sps.isochrones()
print(iso)

getting the error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f05bfc0d10d8> in <module>
----> 1 iso = sps.isochrones()
      2 print(iso)

~/anaconda3/lib/python3.7/site-packages/fsps/fsps.py in isochrones(self, outfile)
    848             self._compute_csp()
    849 
--> 850         from . import ev, list_filters
    851 
    852         absfile = os.path.join(ev, "OUTPUTS", outfile + ".cmd")

ImportError: cannot import name 'ev' from 'fsps' (/home/khushboo_astro/anaconda3/lib/python3.7/site-packages/fsps/__init__.py)
---------------------------------------------------------------------------------

I am not able to understand how to resolve this error. Any suggestions would be appreciated. Thanks!

**Comment by dfm** [comment]
@Dh-hgi: I moved this to #143 since this is a bug that I introduced. Thanks for catching this!

**Comment by bd-j** [comment]
agree on moving to version 0.4 for this release.  I wasn't sure how to release on PYPI but there were enough changes some time ago that I thought a version bump from 0.2 would be a good idea.  I'll work on outstanding issues in the next couple days.

**Comment by dfm** [comment]
As soon as https://github.com/dfm/python-fsps/actions/runs/610833286 finishes, we should have a new release candidate on PyPI that we can test with:

```bash
python -m pip install fsps==0.4.0rc1
```

Let me know if you have issues with that or

```bash
python -m pip install fsps --no-binary fsps
```

which will test the source install. If that works for y'all I'll push a real release in the next couple of days.

**Comment by Dh-hgi** [comment]
Thank you very much!!! I have checked by installing the new version, and it
is working fine now.

**Comment by bd-j** [comment]
@dfm works great! 🥳  Thank you! 🍻

**Comment by dfm** [comment]
Version 0.4 is published 🚀 

https://pypi.org/project/fsps/
