### ISSUE TITLE
Import error in isochrones method

### ISSUE THREAD

**Issue by dfm** [dfm/python-fsps#143]
I have installed FSPS using "python -m pip install fsps==0.3.0rc1"

Now when I am running the code written as

```python
sps = fsps.StellarPopulation(zcontinuous=1)
sps.params['imf_type'] = 0   # Salpeter IMF
sps.params['sfh'] = 1  # Tau model SFH
iso = sps.isochrones()
print(iso)
```

getting the error

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f05bfc0d10d8> in <module>
----> 1 iso = sps.isochrones()
      2 print(iso)

~/anaconda3/lib/python3.7/site-packages/fsps/fsps.py in isochrones(self, outfile)
    848             self._compute_csp()
    849 
--> 850         from . import ev, list_filters
    851 
    852         absfile = os.path.join(ev, "OUTPUTS", outfile + ".cmd")

ImportError: cannot import name 'ev' from 'fsps' (/home/khushboo_astro/anaconda3/lib/python3.7/site-packages/fsps/__init__.py)
---------------------------------------------------------------------------------
```

I am not able to understand how to resolve this error. Any suggestions would be appreciated. Thanks!

_Originally posted by @Dh-hgi in https://github.com/dfm/python-fsps/issues/141#issuecomment-786569880_

**Comment by dfm** [comment]
I think this should be fixed by changing the lines

```python
from . import ev, list_filters

absfile = os.path.join(ev, "OUTPUTS", outfile + ".cmd")
```

to

```python
from . import list_filters

absfile = os.path.join(os.environ["SPS_HOME"], "OUTPUTS", outfile + ".cmd")
```

We should also audit the code to see if this hanging import is anywhere else and the `isochrones` method should also have a test!

I'll try to fix it next week, but I'd also be happy to review a pull request!

**Comment by Dh-hgi** [comment]
Hi,

Thank you very much for the quick response. I have tried making changes in
the fsps.py file, but this is not resolving the issue.

It is probably due to not having access to make changes.  When I am
changing anything in the file, it is marking the changed lines with orange
patches. Kindly see the attached image.

Best regards,
Khushboo

[image: Screenshot from 2021-02-26 22-06-48.png]
*Khushboo Kunwar Rao*
Research Scholar,
Department of Physics,
BITS Pilani, Pilani Campus,
India

**Comment by bd-j** [comment]
I tried the suggested changes and it worked for me (PR coming soon).  Also, just to note that the value of `params["sfh"]` is irrelevant for `isochrones()`; only parameters listed in `params.ssp_params` matter and the weights only come from the IMF, not from the SFH.

**Comment by bd-j** [comment]
Also I don't see `ev` anywhere else in the code.
