### ISSUE TITLE
GitHub actions doesn't catch crashes in Fortran

### ISSUE THREAD

**Issue by dfm** [dfm/python-fsps#154]
As discovered in #153, the CI will happily pass even when the tests immediately crash with a SPS_SETUP error. We should figure out why that is and fix it.

**Comment by dfm** [comment]
This happens because FSPS uses the Fortran keyword `STOP` throughout and that ends the processes but doesn't set a non-zero exit code. It looks like this would be pretty non-trivial to fix without updating the `STOP` usage throughout FSPS. I'll see if I can at least make a test for this.

**Comment by bd-j** [comment]
It probably wouldn't be too difficult for me to replace `STOP` with `STOP -1` or `ERROR STOP -1` throughout FSPS, if that would be a more robust fix.

**Comment by dfm** [comment]
That wouldn't be terrible, I think (I don't know the semantics of Fortran's `STOP` really), but it still wouldn't give the best Pythonic interface. It would be better if it returned something instead of stopping execution because then we could raise an exception. Unfortunately there doesn't seem to be a way of catching exits using F2PY without getting pretty invasive. I've at least created a test to check for this. PR incoming.
