### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bd-j** [dfm/python-fsps#160]
With the upgrade to v3.2 of FSPS, some of the data files moved around.  We should probably have a v0.4.1  release so the PyPI version is consistent and works with with the latest FSPS.

Till then users should install the development version of python-FSPS as described in the docs, or roll back their FSPS to v3.1

**Comment by dfm** [comment]
Classic - Sounds good to me!

It should be enough to just create a new release using the GitHub interface:

- Go to https://github.com/dfm/python-fsps/releases and click "Draft a new release"
- Tag it as `v0.4.1rc1` and call it `python-fsps v0.4.1rc1`, and select the "pre-release" checkbox
- After the tests run, etc. this should push a pre-release to PyPI
- After making sure that that installs as expected, start again at the top and tag `v0.4.1` and don't call it a pre-release.

**Comment by bd-j** [comment]
Thanks for the instructions, and for making it super easy!

**Comment by bd-j** [comment]
0.4.1 is released
