### ISSUE TITLE
No Emission Lines?

### ISSUE THREAD

**Issue by hgc4** [dfm/python-fsps#168]
Hello,
I am making a CSP from an SFH weighted sum of SSPs.

```
ssp = fsps.StellarPopulation(zcontinuous=1,logzsol=np.log10(1.0),sfh=0,imf_type=1,add_neb_emission=True,nebemlineinspec=True)
spec = np.zeros(np.shape(t))
for i in range(len(t)):
    ssp.params['logzsol'] = np.log10(Z[i])
    wave, flux = ssp.get_spectrum(tage=t[i], peraa=True)
    spec += np.array(flux) * sfh[i]
```

I have added the nebular emission flags and verified that spectral lines are being computed; `ssp.emline_luminosity` returns nonzero values. When I plot the spectra (`plt.plot(wave, spec)`) there are no emission lines.

My lookback time array goes close to zero, so there should be some strong emission. Why am I not seeing it in the spectrum?

**Comment by bd-j** [comment]
As a somewhat more self-contained test, can you verify that you do not see emission lines with the following?

```python
import matplotlib.pyplot as pl
import fsps
ssp = fsps.StellarPopulation(zcontinuous=1, logzsol=np.log10(1.0), sfh=0, imf_type=1,
                             add_neb_emission=True, nebemlineinspec=True)
ssp.params['logzsol'] = np.log10(1.0)
wave, flux = ssp.get_spectrum(tage=1e-3, peraa=True)
fig, ax = pl.subplots()
ax.plot(wave, flux)
ax.set_xlim(1e3, 1e4)
ax.set_ylim(0.001, 10)
ax.set_yscale("log")
```

Thanks.

**Comment by hgc4** [comment]
![eml](https://user-images.githubusercontent.com/58079897/127874171-3eae9b92-7ec1-4fb8-813f-45a6c2b9e868.png)
I can see emission lines with this one

**Comment by bd-j** [comment]
Ok, so I think the isse has something to do with your `t` array maybe not going young enough (and should `spec` really have the same shape as `t`?) or the SFH you are using has enough old stars that it washes out the youngest SSP.

Also, see `StellarPopulation.set_tabular_sfh()` which might do what you want in one step.

**Comment by hgc4** [comment]
I experimented by adding random sfh and Z to the end of my data, and still no emlines. Thus, I think the latter is the case. A lot of my sfh data is somewhat skewed to high z, so I will go with that.
Thanks for your help.

**Comment by bd-j** [comment]
Assuming this is resolved, feel free to reopen if there is still a problem with emission lines.
