### ISSUE TITLE
Error for python-fsps installation 

### ISSUE THREAD

**Issue by jizhiyuan** [dfm/python-fsps#169]
Hi,

I am trying to install the python-fsps remotely on a super computer cluster. I got an error information which I do not know how to solve it. I actually see other people encountered the same issue before (https://github.com/dfm/python-fsps/issues/84), but some links provided in the comments are not valid any more I believe. I have tried either the stable or the development version, unfortunately, neither one works.

Just to brief describe the error. I downloaded and installed the python-fsps as:
git clone --recursive https://github.com/dfm/python-fsps.git
cd python-fsps
python -m pip install .

Then, an error info popped up as:
(very very long compiling info ... )
ERROR: Failed building wheel for fsps
Failed to build fsps
ERROR: Could not build wheels for fsps which use PEP 517 and cannot be installed directly

I have no clue how to solve this error. I'd very appreciate any of your help. Thanks in advance

**Comment by dfm** [comment]
Please post the full error message somewhere (perhaps gist.github.com) and share a link.

**Comment by dfm** [comment]
Also: what doesn't work about the stable version? It wouldn't need to compile anything.

**Comment by jizhiyuan** [comment]
Hi, thanks for your quick reply. In fact, I realized that I did not add the gcc module properly to my account at the computer cluster. I have fixed it and installed the stable version successfully. Thanks again
