### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Astropianist** [dfm/python-fsps#170]
Hi Dan,

As we discussed via email, I'm still having issues with the new python-fsps install (with different flags to change the libraries used). 

I was able to get fsps installed in conda. I used the following commands. 

conda install -c conda-forge gfortran
FFLAGS="-DMIST=0 -DPADOVA=1" pip install fsps --no-binary fsps --user

To get it in regular Python, I copied the directories fsps/ and fsps-0.4.1.dist-info/ into the site package library. I had to install gcc@5 (with homebrew) in order to get libgfortran.3.dylib (since the current version of gcc--11--gets libgfortran.5.dylib instead), which is what the conda install seems to use. I'm not 100% sure everything will work, but at least I am at the same point I was at with conda.

Now, the remaining problem is the following. When I create a StellarPopulation instance, I run into a dust emission reading error.

import fsps
sp = fsps.StellarPopulation()
SPS_SETUP ERROR: error opening dust emission file

However, I know that in my fsps directory ($SPS_HOME), the dust emission files are perfectly fine and readable.

**Comment by dfm** [comment]
I cannot reproduce this. The following steps work fine for me on my system:

```bash
(cd $SPS_HOME; git pull)
conda create -n fsps-test -c conda-forge python=3.9 gfortran numpy
conda activate fsps-test
FFLAGS="-DMIST=0 -DPADOVA=1" python -m pip install fsps --no-binary fsps
python -c "import fsps; sp = fsps.StellarPopulation()"
```

You definitely shouldn't need to use a `--user` install and you shouldn't need to copy anything so, if you are, that suggests that there's something wrong with your environment. Try the steps I suggest above and see how that goes.

**Comment by Astropianist** [comment]
It turns out that my FSPS directory was not updated, so git pull in $SPS_HOME ended up solving the issue as changes had been made to the dust emission directory naming scheme. Thanks!
