### ISSUE TITLE
Problem with MILES Spectral Library and Python FSPS

### ISSUE THREAD

**Issue by mkurzner** [dfm/python-fsps#173]
Apologies for the crosspost and if this has been answered previously,  but I have been unable to run Python FSPS recently as every time I try and run Python FSPS and create a stellar population I am getting the following error.

SPS_SETUP ERROR: miles spectral library cannot be opened Z=0.0008

I have attempted to uninstall and reinstall FSPS following the documentation but the issue persists.  I am sure that I am overlooking something here but thank you in advance for the help!

Max

**Comment by dfm** [comment]
@bd-j can probably provide more info, but in the meantime can you tell us exactly how you're installing everything (FSPS itself, and the Python module)?

**Comment by mkurzner** [comment]
Thank you for the quick reply! I am installing FSPS using git and then followed the setup with the Makefile using gfortran to compile everything.  I then pip installed the Python bindings in my $SPS_HOME directory.  I may need to do a full clean reinstallation of FSPS itself too as I just went to my /src folder to try and make the files again and am not running into this error

ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make: *** [simple] Error 1

**Comment by mkurzner** [comment]
I appear to have resolved this issue by uninstalling FSPS and my FORTRAN compiler. I think I can mark this as closed for now but am happy to do a little digging on the cause of this issue as I think I may have had an issue with compiling my code which would not be an issue with FSPS itself.  Thank you again!

Max
