### ISSUE TITLE
Obtain spectral indices for stellar population

### ISSUE THREAD

**Issue by flemesre** [dfm/python-fsps#175]
In section 1.15 of the original FSPS manual, there's a mention of outputting the spectral indices for the desired stellar population using slightly modified syntax for compsps. Is this possible in python-fsps, or do the stellar indices need to be computed "manually"? The documentation makes no mention of stellar indices.

**Comment by moustakas** [comment]
Here's another nice software product, although I have not yet gotten a chance to test it--
  https://gitlab.com/mmoresco/pylick/
