### ISSUE TITLE
Creating a Star-forming Galaxy from sps.isochrones() and its log(weight) output

### ISSUE THREAD

**Issue by pzyao** [dfm/python-fsps#177]
Hi,

We are trying to use the **.isochrones()** function to generate a synthetic CMD assuming a star formation history. However, from what I have read in some of the other issues, it seems like the **sfh** parameter in fsps.StellarPopulation does not affect the output of the isochrones() function. Is there any way to vary the star formation history or the star formation rate, such that the isochrones() function will continue to generate high mass stars in the cmd file that it outputs? If not, what does this parameter (sfh) do to the stellar population we generate? Our understanding is that const = 1 means a constant star formation history for sfh = 1; and const = 0 with a certain value of tau gives a star formation history of the form:
<img width="184" alt="Screen Shot 2022-04-04 at 1 57 52 PM" src="https://user-images.githubusercontent.com/102979323/161603473-0dd8a9a0-eaa3-4837-9439-570a831d5879.png">

One idea we have is from something you mentioned before that 

> "the isochrone data is always given for SSPs of one solar mass formed at each age."

 So does it mean for a composite stellar population (similar to a star-forming galaxy) we need to add together and re-normalize the cmd outputs of multiple ages? In this case, all the data for a given age in the cmd output file (e.g. log(age) = 9) would mean stars in an age bin between (9 and 9.05) Or is there an easier way to do that?

In the end, our goal is to use the output cmd file for the _ArtPop_ code and populate a galaxy with the weights given in the huge output file. So one other thing we want to understand better is the definition of the **log(weight)**. I am equating it to dN/dm in the initial mass function, so that the numerical integral with the analytic form 
<img width="360" alt="Screen Shot 2022-04-04 at 12 18 16 PM" src="https://user-images.githubusercontent.com/102979323/161587790-a555cfca-15e1-4b70-897d-5b922d3ba4b1.png">
with the initial mass "mini" as the mass, and their uneven spacing as each dm. But after experimenting with it for a while, we noticed that this integral for later ages is pretty small (e.g. ~1e-2 for log(age) ~ 9), so we want to know whether our understanding for the definition of **log(weight)** is correct or not.   

Thanks in advance!

**Comment by bd-j** [comment]
Yes, `.isochrones()` gives what you might call "partial CMDs", analogous to SSP spectra but for CMDs.  The `sfh` parameter has no effect on this output (just as it would have no output on the generated SSP spectra), it only affects the output of `get_spectrum` or `get_mags`.  If you want to combine the partial CMDs to represent a composite stellar population, there are several possible ways to go about this; for the scheme implemented in FSPS for SSP spectra see Appendix B of  https://ui.adsabs.harvard.edu/abs/2021ApJS..254...22J/

For composite spectra returned by `get_spectrum` your interpretation of the `const` and `tau` parameters is correct.

For the weights, you should get :math:`sum_i 10**log(weight)_i mini_i \lesssim 1`. The reason it is (slightly) less than 1 is that stars that have died and become remnants simply aren't included in the isochrones, so they will not be included in the sum.  However, I don't think you'll ever get less than 0.3, as most of the mass is contained in low mass stars with long lifetimes.

**Comment by pzyao** [comment]
I see now! Thanks a lot for the prompt response.
