### ISSUE TITLE
arm64 architecture error

### ISSUE THREAD

**Issue by stonnes** [dfm/python-fsps#179]
I am running python in a conda environment and when I try to import fsps I end up getting an error:

from ._fsps import driver
ImportError: dlopen(/Users/stonnesen/python-fsps/src/fsps/_fsps.cpython-38-darwin.so, 0x0002): tried: '/Users/stonnesen/python-fsps/src/fsps/_fsps.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by bd-j** [comment]
Hi @stonnes, I think this is related to #176, and I think the fix was/is to install conda from miniforge because otherwise python runs in a virtualized environment that thinks it's on x86 (while the fortran compilers know they are on arm64)
