### ISSUE TITLE
Undocumented parameters

### ISSUE THREAD

**Issue by dfm** [dfm/python-fsps#2]
There are a few parameters that live in the `pset` structure but don't have any documentation. In the `python-fsps` docs, I've copied over all the documentation about the parameters from the FSPS PDF documentation but it's missing a few parameters (`logzsol`, `pmetals`, `frac_obrun`, `redgb`, `dust1_index`, `masscut`, and `evtype`).

@jonathansick: do you have any idea about what any of these are? If so should we document them or just leave them out like the original documentation does.

**Comment by bd-j** [comment]
fixed by PR #37
