### ISSUE TITLE
Emission line extinction mechanism

### ISSUE THREAD

**Issue by BabisDaoutis** [dfm/python-fsps#216]
Hi,

I was running some models with the FSPS to test the attenuation and extinction. I set the extinction parameter `dust_type = 0` for all models. The first model has `dust1 = 0.7` and `dust2 = 0.3`, while for the second I tried `dust1 = 0.35` and `dust2 = 0.15` (all the other parameters were the same). I noticed that there is a slight difference in the luminosities of the emission lines produced from these two runs. I was wondering the following: 

1) What is the exact extinction mechanism applied to the emission lines?
2) What is the exact attenuation mechanism applied to UV radiation from the stellar populations?
3) How can I control the extinction applied to the emission lines and the UV radiation from the stars separately?

Best,
Babis

**Comment by bd-j** [comment]
Hi @BabisDaoutis 

The attenuation model is based on the Charlot & Fall 2000 two component model.  Briefly, when `add_neb_emission=True` and `nebemlineinspec=True` the emission lines (and nebular continuum) are added to the spectra of 'young' stars, and then the lines *and* young stellar continuum are attenuated by e^(-dust1 * (lambda/5500)^dust1_index).  The result is added to the spectra of the 'old' stars and the sum is *further* attenuated by e^(-dust2 * k_lambda) where k_lambda is the shape of the attenuation curve (a power-law for `dust_type=0`). So you'd expect to see the emission lines be different for different amounts of dust2 or dust1.

The physical picture is that the young stars that are powering the nebular emission would be attenuated by the same dust that affects the nebular continuum itself.  There is no way to attenuate the nebular emission and the young starlight separately.
