### ISSUE TITLE
 SPS_SETUP ERROR: wavelength grid cannot be opened

### ISSUE THREAD

**Issue by Tiantian92** [dfm/python-fsps#258]
Hi, 
I met this problem when I use Prospector: SPS_SETUP ERROR: wavelength grid cannot be opened.
numpy: 1.26.3
scipy: 1.12.0
h5py: 3.10.0
fsps: 0.4.6
prospect: 1.2.0

And I can't do 
cd $SPS_HOME
git pull

**Comment by dfm** [comment]
When you say that you can't do the above command, what do you mean specifically? Can you provide a full report of the error message you see so that we can help debug?

**Comment by Tiantian92** [comment]
Hi, I put the command, the feedback is as following:
---------
(prospector) apple@Apple python-fsps % cd $SPS_HOME
(prospector) apple@Apple fsps-3.2 % git pull    
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> main
-------

**Comment by dfm** [comment]
Thanks - this looks like FSPS was installed using a `.zip` file rather than using git. It also looks like that version is a few years out of date (3.2 was released in May 2021)! I'd recommend following the instructions [in the FSPS README](https://github.com/cconroy20/fsps) to install using git.

**Comment by Tiantian92** [comment]
The problem is resolved!!! Now I can run Prospector.
Thanks!!!
