### ISSUE TITLE
Error in SPS_SETUP

### ISSUE THREAD

**Issue by ssuphakorn** [dfm/python-fsps#265]
Hi,
I tried running fsps on Python but it won't compile. I installed both fsps and python-fsps according to the installation manual. When tested by executing some simple commands such as StellarPopulation, it returns `"SPS_SETUP ERROR:  xsp_feh-2.00.spec cannot be opened"` and Python crashes. I also found that there is no such file in the folder `SPECTRA/xrb/` either.  Using the solution from the [reply](https://github.com/cconroy20/fsps/issues/73) I received from fsps repo page, it turns out that fsps is up to date. Is there any fix to this issue?

For reference, I am using macOS Sonoma (14.0) on my Intel Mac. I also tried compiling the code on a Mac Mini running on M2 chip and similar OS, didn't work either. Python version on both machines is 3.8.18, and was installed via conda. Gfortran on both machines was installed via brew (GCC version 13.2.0).

Best,
SS

**Comment by bd-j** [comment]
Also you can check the installed version;
`python -c "import fsps; print(fsps.__version__)"`

**Comment by ssuphakorn** [comment]
Thank you very much for your suggestion.
Using Python 3.11, I followed your instructions and was able to resolve the issue. Perhaps the reason that my first installation attempt had the older version is I was using Python 3.8? 
Anyway, thank you again for your help.

**Comment by bd-j** [comment]
Great, glad it's working for you.
