### ISSUE TITLE
Question on AGN

### ISSUE THREAD

**Issue by ke27whal** [dfm/python-fsps#276]
If opting to include AGN emission, is the AGN only attenuated by the torus? Or does the galaxy-scale dust also contribute?

**Comment by bd-j** [comment]
Hi, the AGN model _only_ includes the dust emission from the torus as taken from Nenkova 2008, effectively assuming 100% attenuation of the AGN by the torus.  Note the minimum optical depth for the torus (as defined in the Nenkova 2008 models) is 5.
