### ISSUE TITLE
Error when trying to build  on python 2.7

### ISSUE THREAD

**Issue by tamhanepd** [dfm/python-fsps#28]
I have built fsps package, set up $SPS_HOME env variable. I am using Ubuntu 14.04 LTS 64-bit. I modified Makefile as needed and ran "make" in the $SPS_HOME/src directory and everything was built properly without errors. Python2.7 pip version is 1.5.4. I am using revision 143 of the FSPS Fortran API. While trying to build python-fsps using pip, I get following error:
![error1](https://cloud.githubusercontent.com/assets/4407927/5774091/53963a9a-9d90-11e4-85e7-6cc557dc5857.png)
.....
![error](https://cloud.githubusercontent.com/assets/4407927/5773805/dc3e14de-9d8c-11e4-86a5-73f2f0498729.png)

What am I doing wrong? Or is there some problem with my machine?

**Comment by dnarayanan** [comment]
Hi,

I'm not 100% sure, but I think try to recompile FSPS with a -fPIC flag in
F90FLAGS (in the src/Makefile) and it should hopefully work.

-desika

**Comment by dfm** [comment]
That's what I would suggest too! Let us know if that works.

**Comment by bd-j** [comment]
also, you will need one of the following FSPS revisions: 158, 160, 166, 168

We should update the documentation for new revision numbers, add a notice about the -fPIC flag, and give the new link to the code, http://scholar.harvard.edu/cconroy/sps-models or just the googlecode link

**Comment by bd-j** [comment]
or is the r143 version the one available in pip?

**Comment by tamhanepd** [comment]
I don't know if this is the correct way to add the -fPIC flag, but, I have GNU fortran version 4.9, so I edited fortran flags line in  the $SPS_HOME/src/Makefile as follows (FSPS revision 143):
F90FLAGS = -O3 -march=native -cpp -fPIC
and recompiled fsps. Compilation was successful without errors.
Still it gives me the same error while building python-fsps using pip.

When I used FSPS revision 160, it returned this error (I am talking about "pip install fsps"):
ImportError: Your FSPS revision, 160M, is not known to work with this version of python-fsps. You can checkout an accepted FSPS revision with 'svn update -r rev_number'. The accepted FSPS rev_numbers are: [140, 143, 144, 145]

I tried to build using sourcecode, it requires FSPS revision: 158, 160, 166, 168
I used fsps revision 160. It returned following similar error:

![error2](https://cloud.githubusercontent.com/assets/4407927/5783426/bda97a7a-9de8-11e4-8edb-c9cb9add85cc.png)
![error1](https://cloud.githubusercontent.com/assets/4407927/5783429/c500cc7e-9de8-11e4-8045-e2f143457a57.png)

I don't know if I have added the fortran flag correctly. If it is wrong, what is the correct way to put it?

If it is correct, what is causing the problem?

**Comment by bd-j** [comment]
before compiling FSPS r143 and doing the pip install did you do ``make clean`` and then ``make all``?

**Comment by tamhanepd** [comment]
I also request you update the links on the python-fsps page as bd-j suggested. FSPS link is not working (the FSPS page: http://people.ucsc.edu/~conroy/FSPS.html). It says the link is not found.

**Comment by tamhanepd** [comment]
It has compiled successfully with the -fPIC flag. Earlier I did not do make clean. Thanks a lot everyone for your help.
