### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by bdr244** [dfm/python-fsps#30]
Having a bit of trouble with installing this correctly - it seems like it's not finding the fortran FSPS code correctly somehow. I've verified that $SPS_HOME exists and is in the right spot and the necessary files exist (as far as I can tell) but when I go to install python-fsps, it doesn't work.

I've been in communication with Dan about it and the "obvious" fixes aren't working at least, so posting it here to see if anyone else has some suggestions.

Here's the output of the "python setup.py install" command for reference, even though it is a bit of a wall of text.

running install
running bdist_egg
running egg_info
writing fsps.egg-info/PKG-INFO
writing top-level names to fsps.egg-info/top_level.txt
writing dependency_links to fsps.egg-info/dependency_links.txt
reading manifest file 'fsps.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fsps.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/fsps
copying fsps/fsps.py -> build/lib.linux-x86_64-2.7/fsps
copying fsps/filters.py -> build/lib.linux-x86_64-2.7/fsps
copying fsps/tests.py -> build/lib.linux-x86_64-2.7/fsps
copying fsps/__init__.py -> build/lib.linux-x86_64-2.7/fsps
copying fsps/fsps.f90 -> build/lib.linux-x86_64-2.7/fsps
creating build/lib.linux-x86_64-2.7/fsps/data
copying fsps/data/filter_keys.txt -> build/lib.linux-x86_64-2.7/fsps/data
running build_ext
Reading fortran codes...
	Reading file 'fsps.f90' (format:free)
Post-processing...
	Block: _fsps
			Block: driver
In: :_fsps:fsps.f90:driver
get_useparameters: no module sps_utils info used by driver
In: :_fsps:fsps.f90:driver
get_useparameters: no module sps_vars info used by driver
In: :_fsps:fsps.f90:driver
	getarrlen:variable "ntfull" undefined
In: :_fsps:fsps.f90:driver
	getarrlen:variable "nz" undefined
				Block: setup
In: :_fsps:fsps.f90:driver:setup
get_useparameters: no module sps_utils info used by setup
In: :_fsps:fsps.f90:driver:setup
get_useparameters: no module sps_vars info used by setup
				Block: set_ssp_params
In: :_fsps:fsps.f90:driver:set_ssp_params
get_useparameters: no module sps_utils info used by set_ssp_params
In: :_fsps:fsps.f90:driver:set_ssp_params
get_useparameters: no module sps_vars info used by set_ssp_params
				Block: set_csp_params
In: :_fsps:fsps.f90:driver:set_csp_params
get_useparameters: no module sps_utils info used by set_csp_params
In: :_fsps:fsps.f90:driver:set_csp_params
get_useparameters: no module sps_vars info used by set_csp_params
				Block: ssps
In: :_fsps:fsps.f90:driver:ssps
get_useparameters: no module sps_utils info used by ssps
In: :_fsps:fsps.f90:driver:ssps
get_useparameters: no module sps_vars info used by ssps
				Block: ssp
In: :_fsps:fsps.f90:driver:ssp
get_useparameters: no module sps_utils info used by ssp
In: :_fsps:fsps.f90:driver:ssp
get_useparameters: no module sps_vars info used by ssp
				Block: get_ssp_spec
In: :_fsps:fsps.f90:driver:get_ssp_spec
get_useparameters: no module sps_utils info used by get_ssp_spec
In: :_fsps:fsps.f90:driver:get_ssp_spec
get_useparameters: no module sps_vars info used by get_ssp_spec
				Block: interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
get_useparameters: no module sps_utils info used by interp_ssp
In: :_fsps:fsps.f90:driver:interp_ssp
get_useparameters: no module sps_vars info used by interp_ssp
				Block: smooth_spectrum
In: :_fsps:fsps.f90:driver:smooth_spectrum
get_useparameters: no module sps_utils info used by smooth_spectrum
In: :_fsps:fsps.f90:driver:smooth_spectrum
get_useparameters: no module sps_vars info used by smooth_spectrum
				Block: compute
In: :_fsps:fsps.f90:driver:compute
get_useparameters: no module sps_utils info used by compute
In: :_fsps:fsps.f90:driver:compute
get_useparameters: no module sps_vars info used by compute
				Block: get_spec
In: :_fsps:fsps.f90:driver:get_spec
get_useparameters: no module sps_utils info used by get_spec
In: :_fsps:fsps.f90:driver:get_spec
get_useparameters: no module sps_vars info used by get_spec
				Block: get_mags
In: :_fsps:fsps.f90:driver:get_mags
get_useparameters: no module sps_utils info used by get_mags
In: :_fsps:fsps.f90:driver:get_mags
get_useparameters: no module sps_vars info used by get_mags
				Block: get_setup_vars
In: :_fsps:fsps.f90:driver:get_setup_vars
get_useparameters: no module sps_utils info used by get_setup_vars
In: :_fsps:fsps.f90:driver:get_setup_vars
get_useparameters: no module sps_vars info used by get_setup_vars
				Block: get_nz
In: :_fsps:fsps.f90:driver:get_nz
get_useparameters: no module sps_utils info used by get_nz
In: :_fsps:fsps.f90:driver:get_nz
get_useparameters: no module sps_vars info used by get_nz
				Block: get_zlegend
In: :_fsps:fsps.f90:driver:get_zlegend
get_useparameters: no module sps_utils info used by get_zlegend
In: :_fsps:fsps.f90:driver:get_zlegend
get_useparameters: no module sps_vars info used by get_zlegend
				Block: get_timefull
In: :_fsps:fsps.f90:driver:get_timefull
get_useparameters: no module sps_utils info used by get_timefull
In: :_fsps:fsps.f90:driver:get_timefull
get_useparameters: no module sps_vars info used by get_timefull
				Block: get_ntfull
In: :_fsps:fsps.f90:driver:get_ntfull
get_useparameters: no module sps_utils info used by get_ntfull
In: :_fsps:fsps.f90:driver:get_ntfull
get_useparameters: no module sps_vars info used by get_ntfull
				Block: get_nspec
In: :_fsps:fsps.f90:driver:get_nspec
get_useparameters: no module sps_utils info used by get_nspec
In: :_fsps:fsps.f90:driver:get_nspec
get_useparameters: no module sps_vars info used by get_nspec
				Block: get_nbands
In: :_fsps:fsps.f90:driver:get_nbands
get_useparameters: no module sps_utils info used by get_nbands
In: :_fsps:fsps.f90:driver:get_nbands
get_useparameters: no module sps_vars info used by get_nbands
				Block: get_lambda
In: :_fsps:fsps.f90:driver:get_lambda
get_useparameters: no module sps_utils info used by get_lambda
In: :_fsps:fsps.f90:driver:get_lambda
get_useparameters: no module sps_vars info used by get_lambda
				Block: get_isochrone_dimensions
In: :_fsps:fsps.f90:driver:get_isochrone_dimensions
get_useparameters: no module sps_utils info used by get_isochrone_dimensions
In: :_fsps:fsps.f90:driver:get_isochrone_dimensions
get_useparameters: no module sps_vars info used by get_isochrone_dimensions
				Block: get_nmass_isochrone
In: :_fsps:fsps.f90:driver:get_nmass_isochrone
get_useparameters: no module sps_utils info used by get_nmass_isochrone
In: :_fsps:fsps.f90:driver:get_nmass_isochrone
get_useparameters: no module sps_vars info used by get_nmass_isochrone
				Block: get_stats
In: :_fsps:fsps.f90:driver:get_stats
get_useparameters: no module sps_utils info used by get_stats
In: :_fsps:fsps.f90:driver:get_stats
get_useparameters: no module sps_vars info used by get_stats
				Block: get_isochrone
In: :_fsps:fsps.f90:driver:get_isochrone
get_useparameters: no module sps_utils info used by get_isochrone
In: :_fsps:fsps.f90:driver:get_isochrone
get_useparameters: no module sps_vars info used by get_isochrone
In: :_fsps:fsps.f90:driver:get_isochrone
	getarrlen:variable "nbands" undefined
In: :_fsps:fsps.f90:driver:get_isochrone
	getarrlen:variable "nm" undefined
In: :_fsps:fsps.f90:driver:get_isochrone
	getarrlen:variable "nspec" undefined
				Block: write_isoc
In: :_fsps:fsps.f90:driver:write_isoc
get_useparameters: no module sps_utils info used by write_isoc
In: :_fsps:fsps.f90:driver:write_isoc
get_useparameters: no module sps_vars info used by write_isoc
Post-processing (stage 2)...
	Block: _fsps
		Block: unknown_interface
			Block: driver
				Block: setup
				Block: set_ssp_params
				Block: set_csp_params
				Block: ssps
				Block: ssp
				Block: get_ssp_spec
				Block: interp_ssp
				Block: smooth_spectrum
				Block: compute
				Block: get_spec
				Block: get_mags
				Block: get_setup_vars
				Block: get_nz
				Block: get_zlegend
				Block: get_timefull
				Block: get_ntfull
				Block: get_nspec
				Block: get_nbands
				Block: get_lambda
				Block: get_isochrone_dimensions
				Block: get_nmass_isochrone
				Block: get_stats
				Block: get_isochrone
				Block: write_isoc
Saving signatures to file "./fsps.pyf"
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_fsps" sources
creating /tmp/tmp7aJuAU/src.linux-x86_64-2.7
f2py options: []
f2py: fsps.pyf
Reading fortran codes...
	Reading file 'fsps.pyf' (format:free)
Post-processing...
	Block: _fsps
			Block: driver
In: fsps.pyf:_fsps:unknown_interface:driver
get_useparameters: no module sps_utils info used by driver
In: fsps.pyf:_fsps:unknown_interface:driver
get_useparameters: no module sps_vars info used by driver
				Block: setup
In: fsps.pyf:_fsps:unknown_interface:driver:setup
get_useparameters: no module sps_utils info used by setup
In: fsps.pyf:_fsps:unknown_interface:driver:setup
get_useparameters: no module sps_vars info used by setup
				Block: set_ssp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_ssp_params
get_useparameters: no module sps_utils info used by set_ssp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_ssp_params
get_useparameters: no module sps_vars info used by set_ssp_params
				Block: set_csp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_csp_params
get_useparameters: no module sps_utils info used by set_csp_params
In: fsps.pyf:_fsps:unknown_interface:driver:set_csp_params
get_useparameters: no module sps_vars info used by set_csp_params
				Block: ssps
In: fsps.pyf:_fsps:unknown_interface:driver:ssps
get_useparameters: no module sps_utils info used by ssps
In: fsps.pyf:_fsps:unknown_interface:driver:ssps
get_useparameters: no module sps_vars info used by ssps
				Block: ssp
In: fsps.pyf:_fsps:unknown_interface:driver:ssp
get_useparameters: no module sps_utils info used by ssp
In: fsps.pyf:_fsps:unknown_interface:driver:ssp
get_useparameters: no module sps_vars info used by ssp
				Block: get_ssp_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_ssp_spec
get_useparameters: no module sps_utils info used by get_ssp_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_ssp_spec
get_useparameters: no module sps_vars info used by get_ssp_spec
				Block: interp_ssp
In: fsps.pyf:_fsps:unknown_interface:driver:interp_ssp
get_useparameters: no module sps_utils info used by interp_ssp
In: fsps.pyf:_fsps:unknown_interface:driver:interp_ssp
get_useparameters: no module sps_vars info used by interp_ssp
				Block: smooth_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:smooth_spectrum
get_useparameters: no module sps_utils info used by smooth_spectrum
In: fsps.pyf:_fsps:unknown_interface:driver:smooth_spectrum
get_useparameters: no module sps_vars info used by smooth_spectrum
				Block: compute
In: fsps.pyf:_fsps:unknown_interface:driver:compute
get_useparameters: no module sps_utils info used by compute
In: fsps.pyf:_fsps:unknown_interface:driver:compute
get_useparameters: no module sps_vars info used by compute
				Block: get_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_spec
get_useparameters: no module sps_utils info used by get_spec
In: fsps.pyf:_fsps:unknown_interface:driver:get_spec
get_useparameters: no module sps_vars info used by get_spec
				Block: get_mags
In: fsps.pyf:_fsps:unknown_interface:driver:get_mags
get_useparameters: no module sps_utils info used by get_mags
In: fsps.pyf:_fsps:unknown_interface:driver:get_mags
get_useparameters: no module sps_vars info used by get_mags
				Block: get_setup_vars
In: fsps.pyf:_fsps:unknown_interface:driver:get_setup_vars
get_useparameters: no module sps_utils info used by get_setup_vars
In: fsps.pyf:_fsps:unknown_interface:driver:get_setup_vars
get_useparameters: no module sps_vars info used by get_setup_vars
				Block: get_nz
In: fsps.pyf:_fsps:unknown_interface:driver:get_nz
get_useparameters: no module sps_utils info used by get_nz
In: fsps.pyf:_fsps:unknown_interface:driver:get_nz
get_useparameters: no module sps_vars info used by get_nz
				Block: get_zlegend
In: fsps.pyf:_fsps:unknown_interface:driver:get_zlegend
get_useparameters: no module sps_utils info used by get_zlegend
In: fsps.pyf:_fsps:unknown_interface:driver:get_zlegend
get_useparameters: no module sps_vars info used by get_zlegend
				Block: get_timefull
In: fsps.pyf:_fsps:unknown_interface:driver:get_timefull
get_useparameters: no module sps_utils info used by get_timefull
In: fsps.pyf:_fsps:unknown_interface:driver:get_timefull
get_useparameters: no module sps_vars info used by get_timefull
				Block: get_ntfull
In: fsps.pyf:_fsps:unknown_interface:driver:get_ntfull
get_useparameters: no module sps_utils info used by get_ntfull
In: fsps.pyf:_fsps:unknown_interface:driver:get_ntfull
get_useparameters: no module sps_vars info used by get_ntfull
				Block: get_nspec
In: fsps.pyf:_fsps:unknown_interface:driver:get_nspec
get_useparameters: no module sps_utils info used by get_nspec
In: fsps.pyf:_fsps:unknown_interface:driver:get_nspec
get_useparameters: no module sps_vars info used by get_nspec
				Block: get_nbands
In: fsps.pyf:_fsps:unknown_interface:driver:get_nbands
get_useparameters: no module sps_utils info used by get_nbands
In: fsps.pyf:_fsps:unknown_interface:driver:get_nbands
get_useparameters: no module sps_vars info used by get_nbands
				Block: get_lambda
In: fsps.pyf:_fsps:unknown_interface:driver:get_lambda
get_useparameters: no module sps_utils info used by get_lambda
In: fsps.pyf:_fsps:unknown_interface:driver:get_lambda
get_useparameters: no module sps_vars info used by get_lambda
				Block: get_isochrone_dimensions
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone_dimensions
get_useparameters: no module sps_utils info used by get_isochrone_dimensions
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone_dimensions
get_useparameters: no module sps_vars info used by get_isochrone_dimensions
				Block: get_nmass_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_nmass_isochrone
get_useparameters: no module sps_utils info used by get_nmass_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_nmass_isochrone
get_useparameters: no module sps_vars info used by get_nmass_isochrone
				Block: get_stats
In: fsps.pyf:_fsps:unknown_interface:driver:get_stats
get_useparameters: no module sps_utils info used by get_stats
In: fsps.pyf:_fsps:unknown_interface:driver:get_stats
get_useparameters: no module sps_vars info used by get_stats
				Block: get_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone
get_useparameters: no module sps_utils info used by get_isochrone
In: fsps.pyf:_fsps:unknown_interface:driver:get_isochrone
get_useparameters: no module sps_vars info used by get_isochrone
				Block: write_isoc
In: fsps.pyf:_fsps:unknown_interface:driver:write_isoc
get_useparameters: no module sps_utils info used by write_isoc
In: fsps.pyf:_fsps:unknown_interface:driver:write_isoc
get_useparameters: no module sps_vars info used by write_isoc
Post-processing (stage 2)...
	Block: _fsps
		Block: unknown_interface
			Block: driver
				Block: setup
				Block: set_ssp_params
				Block: set_csp_params
				Block: ssps
				Block: ssp
				Block: get_ssp_spec
				Block: interp_ssp
				Block: smooth_spectrum
				Block: compute
				Block: get_spec
				Block: get_mags
				Block: get_setup_vars
				Block: get_nz
				Block: get_zlegend
				Block: get_timefull
				Block: get_ntfull
				Block: get_nspec
				Block: get_nbands
				Block: get_lambda
				Block: get_isochrone_dimensions
				Block: get_nmass_isochrone
				Block: get_stats
				Block: get_isochrone
				Block: write_isoc
Building modules...
	Building module "_fsps"...
		Constructing F90 module support for "driver"...
		  Variables: is_setup
			Constructing wrapper function "driver.setup"...
			  setup(compute_vega_mags0,redshift_colors0,smooth_velocity0,add_stellar_remnants0,add_neb_emission0,add_dust_emission0,add_agb_dust_model0,tpagb_norm_type0)
			Constructing wrapper function "driver.set_ssp_params"...
			  set_ssp_params(imf_type0,imf1,imf2,imf3,vdmc,mdave,dell,delt,sbss,fbhb,pagb,agb_dust,redgb,masscut,fcstar,evtype)
			Constructing wrapper function "driver.set_csp_params"...
			  set_csp_params(dust_type0,zmet,sfh,wgp1,wgp2,wgp3,tau,const_bn,tage,fburst,tburst,dust1,dust2,logzsol,zred,pmetals,dust_clumps,frac_nodust,dust_index,dust_tesc,frac_obrun,uvb,mwr,dust1_index,sf_start,sf_trunc,sf_theta,duste_gamma,duste_umin,duste_qpah,sigma_smooth,min_wave_smooth,max_wave_smooth)
			Constructing wrapper function "driver.ssps"...
			  ssps()
			Constructing wrapper function "driver.ssp"...
			  ssp(zi)
			Constructing wrapper function "driver.get_ssp_spec"...
			  get_ssp_spec(ssp_spec_out,ssp_mass_out,ssp_lbol_out,[ns,n_age,n_z])
			Constructing wrapper function "driver.interp_ssp"...
			  interp_ssp(zpos,tpos,spec,mass,lbol,[ns])
			Constructing wrapper function "driver.smooth_spectrum"...
			  smooth_spectrum(wave,spec,sigma_broad,minw,maxw,[ns])
			Constructing wrapper function "driver.compute"...
			  compute()
			Constructing wrapper function "driver.get_spec"...
			  spec_out = get_spec(ns,n_age)
			Constructing wrapper function "driver.get_mags"...
			  mags = get_mags(n_age,z_red,mc,[n_bands])
			Constructing wrapper function "driver.get_setup_vars"...
			  cvms,rcolors,svel,asr,ane,ade,agbd,agbn = get_setup_vars()
			Constructing wrapper function "driver.get_nz"...
			  n_z = get_nz()
			Constructing wrapper function "driver.get_zlegend"...
			  z_legend = get_zlegend(n_z)
			Constructing wrapper function "driver.get_timefull"...
			  timefull = get_timefull(n_age)
			Constructing wrapper function "driver.get_ntfull"...
			  n_age = get_ntfull()
			Constructing wrapper function "driver.get_nspec"...
			  ns = get_nspec()
			Constructing wrapper function "driver.get_nbands"...
			  nb = get_nbands()
			Constructing wrapper function "driver.get_lambda"...
			  lambda = get_lambda(ns)
			Constructing wrapper function "driver.get_isochrone_dimensions"...
			  n_age,n_mass = get_isochrone_dimensions()
			Constructing wrapper function "driver.get_nmass_isochrone"...
			  nmass = get_nmass_isochrone(zz,tt)
			Constructing wrapper function "driver.get_stats"...
			  age,mass_csp,lbol_csp,sfr,mdust = get_stats(n_age)
			Constructing wrapper function "driver.get_isochrone"...
			  time_out,z_out,mass_init_out,logl_out,logt_out,logg_out,ffco_out,phase_out,wght_out,mags_out = get_isochrone(zz,tt,n_mass,n_mags)
			Constructing wrapper function "driver.write_isoc"...
			  write_isoc(outfile)
	Wrote C/API module "_fsps" to file "/tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fspsmodule.c"
	Fortran 90 wrappers are saved to "/tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fsps-f2pywrappers2.f90"
  adding '/tmp/tmp7aJuAU/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding '/tmp/tmp7aJuAU/src.linux-x86_64-2.7' to include_dirs.
copying /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmp7aJuAU/src.linux-x86_64-2.7
copying /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmp7aJuAU/src.linux-x86_64-2.7
  adding '/tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fsps-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building '_fsps' extension
compiling C sources
C compiler: gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating /tmp/tmp7aJuAU/tmp
creating /tmp/tmp7aJuAU/tmp/tmp7aJuAU
creating /tmp/tmp7aJuAU/tmp/tmp7aJuAU/src.linux-x86_64-2.7
compile options: '-I/home/data/bdr244/Desktop/fsps-read-only/src -I/tmp/tmp7aJuAU/src.linux-x86_64-2.7 -I/home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include -I/home/data/bdr244/anaconda/include/python2.7 -c'
gcc: /tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fspsmodule.c
In file included from /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804,
                 from /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmp7aJuAU/src.linux-x86_64-2.7/fortranobject.h:13,
                 from /tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fspsmodule.c:18:
/home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
/tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fspsmodule.c:144: warning: ‘f2py_size’ defined but not used
gcc: /tmp/tmp7aJuAU/src.linux-x86_64-2.7/fortranobject.c
In file included from /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804,
                 from /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmp7aJuAU/src.linux-x86_64-2.7/fortranobject.h:13,
                 from /tmp/tmp7aJuAU/src.linux-x86_64-2.7/fortranobject.c:2:
/home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
compiling Fortran 90 module sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -fPIC -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -fPIC -O3 -funroll-loops
compile options: '-I/home/data/bdr244/Desktop/fsps-read-only/src -I/tmp/tmp7aJuAU/src.linux-x86_64-2.7 -I/home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include -I/home/data/bdr244/anaconda/include/python2.7 -c'
extra options: '-J/tmp/tmp7aJuAU/ -I/tmp/tmp7aJuAU/'
gfortran:f90: fsps.f90
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -fPIC -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -fPIC -O3 -funroll-loops
compile options: '-I/home/data/bdr244/Desktop/fsps-read-only/src -I/tmp/tmp7aJuAU/src.linux-x86_64-2.7 -I/home/data/bdr244/anaconda/lib/python2.7/site-packages/numpy/core/include -I/home/data/bdr244/anaconda/include/python2.7 -c'
extra options: '-J/tmp/tmp7aJuAU/ -I/tmp/tmp7aJuAU/'
gfortran:f90: /tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fsps-f2pywrappers2.f90
/usr/bin/gfortran -Wall -g -Wall -g -shared /tmp/tmp7aJuAU/tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fspsmodule.o /tmp/tmp7aJuAU/tmp/tmp7aJuAU/src.linux-x86_64-2.7/fortranobject.o /tmp/tmp7aJuAU/fsps.o /tmp/tmp7aJuAU/tmp/tmp7aJuAU/src.linux-x86_64-2.7/_fsps-f2pywrappers2.o /home/data/bdr244/Desktop/fsps-read-only/src/tsum.o /home/data/bdr244/Desktop/fsps-read-only/src/sps_setup.o /home/data/bdr244/Desktop/fsps-read-only/src/vacairconv.o /home/data/bdr244/Desktop/fsps-read-only/src/imf_weight.o /home/data/bdr244/Desktop/fsps-read-only/src/igm_absorb.o /home/data/bdr244/Desktop/fsps-read-only/src/write_isochrone.o /home/data/bdr244/Desktop/fsps-read-only/src/linterparr.o /home/data/bdr244/Desktop/fsps-read-only/src/getmags.o /home/data/bdr244/Desktop/fsps-read-only/src/smoothspec.o /home/data/bdr244/Desktop/fsps-read-only/src/mod_gb.o /home/data/bdr244/Desktop/fsps-read-only/src/sbf.o /home/data/bdr244/Desktop/fsps-read-only/src/sfhstat.o /home/data/bdr244/Desktop/fsps-read-only/src/add_bs.o /home/data/bdr244/Desktop/fsps-read-only/src/ztinterp.o /home/data/bdr244/Desktop/fsps-read-only/src/add_nebular.o /home/data/bdr244/Desktop/fsps-read-only/src/sps_vars.o /home/data/bdr244/Desktop/fsps-read-only/src/pz_convol.o /home/data/bdr244/Desktop/fsps-read-only/src/funcint.o /home/data/bdr244/Desktop/fsps-read-only/src/add_dust.o /home/data/bdr244/Desktop/fsps-read-only/src/get_lumdist.o /home/data/bdr244/Desktop/fsps-read-only/src/add_remnants.o /home/data/bdr244/Desktop/fsps-read-only/src/linterp.o /home/data/bdr244/Desktop/fsps-read-only/src/mod_hb.o /home/data/bdr244/Desktop/fsps-read-only/src/compsp.o /home/data/bdr244/Desktop/fsps-read-only/src/getspec.o /home/data/bdr244/Desktop/fsps-read-only/src/sps_utils.o /home/data/bdr244/Desktop/fsps-read-only/src/getindx.o /home/data/bdr244/Desktop/fsps-read-only/src/imf.o /home/data/bdr244/Desktop/fsps-read-only/src/add_agb_dust.o /home/data/bdr244/Desktop/fsps-read-only/src/ssp_gen.o /home/data/bdr244/Desktop/fsps-read-only/src/locate.o /home/data/bdr244/Desktop/fsps-read-only/src/get_tuniv.o -L/home/data/bdr244/anaconda/lib -lpython2.7 -lgfortran -o ./_fsps.so
/usr/bin/ld: /home/data/bdr244/Desktop/fsps-read-only/src/sps_setup.o: relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/data/bdr244/Desktop/fsps-read-only/src/sps_setup.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
/usr/bin/ld: /home/data/bdr244/Desktop/fsps-read-only/src/sps_setup.o: relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/data/bdr244/Desktop/fsps-read-only/src/sps_setup.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
Running: cd fsps;f2py fsps.f90 -m _fsps -h fsps.pyf --overwrite-signature
Running: cd fsps;f2py -c -I/home/data/bdr244/Desktop/fsps-read-only/src /home/data/bdr244/Desktop/fsps-read-only/src/tsum.o /home/data/bdr244/Desktop/fsps-read-only/src/sps_setup.o /home/data/bdr244/Desktop/fsps-read-only/src/vacairconv.o /home/data/bdr244/Desktop/fsps-read-only/src/imf_weight.o /home/data/bdr244/Desktop/fsps-read-only/src/igm_absorb.o /home/data/bdr244/Desktop/fsps-read-only/src/write_isochrone.o /home/data/bdr244/Desktop/fsps-read-only/src/linterparr.o /home/data/bdr244/Desktop/fsps-read-only/src/getmags.o /home/data/bdr244/Desktop/fsps-read-only/src/smoothspec.o /home/data/bdr244/Desktop/fsps-read-only/src/mod_gb.o /home/data/bdr244/Desktop/fsps-read-only/src/sbf.o /home/data/bdr244/Desktop/fsps-read-only/src/sfhstat.o /home/data/bdr244/Desktop/fsps-read-only/src/add_bs.o /home/data/bdr244/Desktop/fsps-read-only/src/ztinterp.o /home/data/bdr244/Desktop/fsps-read-only/src/add_nebular.o /home/data/bdr244/Desktop/fsps-read-only/src/sps_vars.o /home/data/bdr244/Desktop/fsps-read-only/src/pz_convol.o /home/data/bdr244/Desktop/fsps-read-only/src/funcint.o /home/data/bdr244/Desktop/fsps-read-only/src/add_dust.o /home/data/bdr244/Desktop/fsps-read-only/src/get_lumdist.o /home/data/bdr244/Desktop/fsps-read-only/src/add_remnants.o /home/data/bdr244/Desktop/fsps-read-only/src/linterp.o /home/data/bdr244/Desktop/fsps-read-only/src/mod_hb.o /home/data/bdr244/Desktop/fsps-read-only/src/compsp.o /home/data/bdr244/Desktop/fsps-read-only/src/getspec.o /home/data/bdr244/Desktop/fsps-read-only/src/sps_utils.o /home/data/bdr244/Desktop/fsps-read-only/src/getindx.o /home/data/bdr244/Desktop/fsps-read-only/src/imf.o /home/data/bdr244/Desktop/fsps-read-only/src/add_agb_dust.o /home/data/bdr244/Desktop/fsps-read-only/src/ssp_gen.o /home/data/bdr244/Desktop/fsps-read-only/src/locate.o /home/data/bdr244/Desktop/fsps-read-only/src/get_tuniv.o fsps.f90 fsps.pyf --f90flags=-cpp --f90flags=-fPIC
Moving /home/data/bdr244/python-fsps/fsps/_fsps.so to /home/data/bdr244/python-fsps/build/lib.linux-x86_64-2.7/fsps/_fsps.so

**Comment by bd-j** [comment]
there is a line ``can not be used when making a shared object; recompile with -fPIC`` in your log
 You can try recompiling FSPS with the ``-fPIC`` compiler flag, hopefully that will solve the problem.  Do this by changing the FSPS Makefile in fsps/src/ to add the compiler flag, then typing ``make clean`` and then ``make all``.  

Let us know if that works!

**Comment by bdr244** [comment]
That nailed it - I just had to add that flag to the FSPS compilation. Thank you!

**Comment by bdr244** [comment]
That nailed it - I just had to add that flag to the FSPS compilation. Thank you!
