### ISSUE TITLE
FSPS -fPIC

### ISSUE THREAD

**Issue by bd-j** [dfm/python-fsps#31]
Make sure the installation documentation mentions that FSPS should be compiled with the -fPIC compiler flag.  It would also be great if we could catch this error some way during the build and report it in a human readable way.

**Comment by dfm** [comment]
This would be great! I forget every single time!!!

**Comment by jonathansick** [comment]
Hold on, I only have `F90FLAGS = -O3 -cpp` in my FSPS Makefile and everything is happy. What's going on here?

```
gfortran --version
GNU Fortran (Homebrew gcc 4.9.2) 4.9.2
```

**Comment by bd-j** [comment]
actually I have the same (homebrew gfortran 4.9.2 and no fPIC flag)!  But I've had to use fPIC when using other compilers/machines

**Comment by jonathansick** [comment]
I'll add it as build advice in a documentation update PR later.

**Comment by bd-j** [comment]
this is in the documentation as of v0.2.1
