### ISSUE TITLE
Does't work with new FSPS on Github 

### ISSUE THREAD

**Issue by dr-guangtou** [dfm/python-fsps#32]
After updating to the new version of FSPS on Github, it seems that the installation of python-fsps will fail, since there is no SVN version now.  

    # Check the SVN revision number.
    ACCEPTED_FSPS_REVISIONS = [158, 160, 166, 168, 170, 185]
    cmd = ["svnversion", ev]
    stat, out = run_command(" ".join(cmd))
    fsps_vers = int(re.match("^([0-9])+", out[0]).group(0))

If simply comments this part out, and give `accepted = True`, the installation will run through, and basic functions seem work fine.  But I am not sure this should be the right solution...

Thanks!

**Comment by bd-j** [comment]
Yes, for FSPS on github we should delete this check entirely, or do a check on the githash.  We also need to update the documentation.

**Comment by dr-guangtou** [comment]
@bd-j Thanks!  So, I assume it should be safe for me to keep using python-fsps this way, temporarily?

**Comment by bd-j** [comment]
Yes, the github version, which was r191 or so in svn, should still be compatible.

**Comment by dr-guangtou** [comment]
Great ! Thanks!

**Comment by dnarayanan** [comment]
actually - should this be closed? it seems like since the fsps repo being stored in github is the way forward, that it might be useful to keep it open as a reminder that pyfsps should check for the githash of FSPS

**Comment by bd-j** [comment]
I just opened a new issue to cover this with a more precise title.

**Comment by dnarayanan** [comment]
Hi All,

Related to this - does python-fsps require only somewhat older (like <170)
SVN versions of fsps?  I think I get from Ben's email below that 191 could
work, though any time I try to install python-fsps for a recent SVN version
of fsps, it barfs and tells me I need to roll back.  I'd like to run the
latest version of possible, so thought I'd check.

thanks
-d

**Comment by bd-j** [comment]
The accepted revisions are *known* to work with python-FSPS.  Later revisions *might* work.  In fact r191 should work, though you won't have access through python-FSPS to some of the new variables, though you can set them via sps_vars.f90 in FSPS.  PR #27  addresses this (and in fact requires svnversion > r171)

All that said, if you comment out the revision check in fsps/__init__.py like in the original post, the current version of python-fsps/master should work with r191 or the github version
