### ISSUE TITLE
update for FSPS on github

### ISSUE THREAD

**Issue by bd-j** [dfm/python-fsps#33]
FSPS is now on github instead of googlecode!

This means we need to replace the svn revision check with a githash check.  Also we need to update the documentation about where/how FSPS can be downloaded and installed.

**Comment by astronomeralex** [comment]
i was wondering if there's a way to still download fsps via google code? i'd like to be able to use python-fsps, but currently can't since I downloaded fsps from github.

**Comment by dnarayanan** [comment]
hey alex - this still works for me:

> svn checkout http://fsps.googlecode.com/svn/trunk/ fsps

**Comment by bd-j** [comment]
I just merged #34. Sorry for the delay

**Comment by bd-j** [comment]
Though there's actually still a bug.  Waiting for a PR from @nell-byler to fix (see a80424e1)

**Comment by astronomeralex** [comment]
thanks, i was just about to report that bug, too :)

**Comment by bd-j** [comment]
We've got the fix in, though the history is now a little weird.
