### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by dweisz** [dfm/python-fsps#43]
Just did a fresh install of fsps and then python-fsps.  fsps installation was fine, and all tests works. But installing python-fsps gives:

...
byte-compiling build/bdist.macosx-10.5-x86_64/egg/fsps/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/fsps/filters.py to filters.cpython-34.pyc
  File "build/bdist.macosx-10.5-x86_64/egg/fsps/filters.py", line 88
    except KeyError, e:
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.5-x86_64/egg/fsps/fsps.py to fsps.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/fsps/tests.py to tests.cpython-34.pyc
...

and then within python:

IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import fsps
  File "/Users/dweisz/Documents/code/python-fsps/fsps/filters.py", line 88
    except KeyError, e:
                   ^
SyntaxError: invalid syntax

Not sure what's going on here.  Suggestions?

**Comment by bd-j** [comment]
Are you using python 3?  That's the most likely issue.

Otherwise, make sure you are on the master branch for both fsps and python-fsps --- I have no problems installing those.

**Comment by bd-j** [comment]
It looks like python3 will break a number of other things, especially related to the iteritems access to the ParameterSet

**Comment by dfm** [comment]
Either way, that should be rewritten as `except KeyError as e`. That's been the right syntax since Python 2.6 or something and it would work on 3 too!

**Comment by bd-j** [comment]
I have a PR (#44) for that and the iterator issue, but don't have python3 installed yet to test

**Comment by dweisz** [comment]
Just to confirm, python-fsps installed just fine for me when using python 2.7.

**Comment by bd-j** [comment]
this should be fixed with the merge of PR #44, so closing
