### ISSUE TITLE
small fluxes due to KC13 dust curve

### ISSUE THREAD

**Issue by jrleja** [dfm/python-fsps#47]
The KC13 curve has a huge turn up towards the UV, which results in very small fluxes that get turned into NaNs when accessed by the fortran parts of python-FSPS.  This results in issues when calculating magnitudes. Age interpolation and redshifting both remove the NaNs, so this is only an issue when tage is set to a native FSPS age.

Here's a minimum working example:

sps = fsps.StellarPopulation()
sps.params['sfh'] = 1.0
sps.params['dust_type'] = 4
sps.params['tage'] = 1.0
sps.params['dust2'] = 0.05

mags = sps.get_mags(tage=sps.params['tage'])
print mags

**Comment by bd-j** [comment]
I think this is fixed in FSPS v2.6 where there's now a check in compsp for very small numbers, which would otherwise underflow.  Closing
