### ISSUE TITLE
installation issues with gcc

### ISSUE THREAD

**Issue by dnarayanan** [dfm/python-fsps#56]
I'm having some troubles installing py-fsps with gcc.  I'm on a new cluster, with the following:

```
desika.narayanan@gator4 python-fsps]$ module list

Currently Loaded Modules:
  1) git/1.9.0   2) gcc/5.2.0   3) openmpi/1.10.0

[desika.narayanan@gator4 python-fsps]$ which gfortran
/apps/compilers/gcc/5.2.0/bin/gfortran

[desika.narayanan@gator4 python-fsps]$ ls /apps/compilers/gcc/5.2.0/bin
aot-compile*  gappletviewer*  gcc-nm*      gcjh*       gij*         gkeytool*       grmid*         jcf-dump*                      x86_64-unknown-linux-gnu-g++*        x86_64-unknown-linux-gnu-gcc-nm*
c++*          gc-analyze*     gcc-ranlib*  gcov*       gjar*        gnative2ascii*  grmiregistry*  jv-convert*                    x86_64-unknown-linux-gnu-gcc*        x86_64-unknown-linux-gnu-gcc-ranlib*
cpp*          gcc*            gcj*         gcov-tool*  gjarsigner*  gorbd*          gserialver*    rebuild-gcj-db*                x86_64-unknown-linux-gnu-gcc-5.2.0*  x86_64-unknown-linux-gnu-gcj*
g++*          gcc-ar*         gcj-dbtool*  gfortran*   gjavah*      grmic*          gtnameserv*    x86_64-unknown-linux-gnu-c++*  x86_64-unknown-linux-gnu-gcc-ar*     x86_64-unknown-linux-gnu-gfortran*
[desika.narayanan@gator4 python-fsps]$
```

fsps compiles with no problem.  In particular, in the fsps Makefile, I use the options:

```
# GNU
F90 = gfortran

#========================
# Compiler Optimizations
#  (Uncomment only one)
#========================
# GNU (version < 4.3.0)
#F90FLAGS = -O -cpp
# GNU (version >= 4.3.0)
F90FLAGS = -O3 -march=native -cpp -fPIC

```

and no issues in compilation.  However, when compiling py-fsps, I get some error looking for f95.    It's a bit odd since I can compile with other versions of gfortran with no problem.  Am I possibly missing a python package?

```
[desika.narayanan@gator4 python-fsps]$ python setup.py install
...
.....
gcc: /tmp/tmpLM7bE4/src.linux-x86_64-2.7/_fspsmodule.c
In file included from /home/desika.narayanan/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /home/desika.narayanan/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/desika.narayanan/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmpLM7bE4/src.linux-x86_64-2.7/fortranobject.h:13,
                 from /tmp/tmpLM7bE4/src.linux-x86_64-2.7/_fspsmodule.c:19:
/home/desika.narayanan/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
/tmp/tmpLM7bE4/src.linux-x86_64-2.7/_fspsmodule.c:145:12: warning: ‘f2py_size’ defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject* var, ...)
            ^
compiling Fortran 90 module sources
Fortran f77 compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: f95 -fPIC -fPIC -O3 -funroll-loops
Fortran fix compiler: f95 -Wall -g -ffixed-form -fno-second-underscore -fPIC -fPIC -O3 -funroll-loops
compile options: '-I/home/desika.narayanan/pd//fsps/src -I/tmp/tmpLM7bE4/src.linux-x86_64-2.7 -I/home/desika.narayanan/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/home/desika.narayanan/miniconda2/include/python2.7 -c'
extra options: '-J/tmp/tmpLM7bE4/ -I/tmp/tmpLM7bE4/'
f95:f90: fsps.f90
sh: f95: command not found
sh: f95: command not found
error: Command "f95 -fPIC -fPIC -O3 -funroll-loops -I/home/desika.narayanan/pd//fsps/src -I/tmp/tmpLM7bE4/src.linux-x86_64-2.7 -I/home/desika.narayanan/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/home/desika.narayanan/miniconda2/include/python2.7 -c -c fsps.f90 -o /tmp/tmpLM7bE4/fsps.o -J/tmp/tmpLM7bE4/ -I/tmp/tmpLM7bE4/" failed with exit status 127

```

**Comment by bd-j** [comment]
python-FSPS installation uses the f2py package included with numpy, which is configured to use certain compilers.  It looks like numpy/f2py isn't configured quite right, and is trying to use a compiler that doesn't exist.

One workaround might be to alias gfortran to the f95 executable....

**Comment by dnarayanan** [comment]
Thanks Ben!

At the risk of being naive - do you mean a simple export F95=gfortran ?

(if so, this doesn't work.)

thanks
-d

**Comment by bd-j** [comment]
Hi Desika,
Sorry,  try
```
alias f95='gfortran'
```

Another thing to try is to see if your cluster has a specific python module(s) for python and/or numpy, and make sure that module is loaded.

**Comment by dnarayanan** [comment]
hmm unfortunately that doesn't work either.

[desika.narayanan@gator4 python-fsps]$ export
f95='/apps/compilers/gcc/5.2.0/bin/gfortran'
[desika.narayanan@gator4 python-fsps]$ echo $f95
/apps/compilers/gcc/5.2.0/bin/gfortran

I'll see if I can figure out how to get f2py to not look for f95.  I've had
it work before, all using both gfortran and anaconda so will see if I can
figure out what's different in the numpy versions and gfortran versions...

-d

**Comment by bd-j** [comment]
It would have to be ``alias`` not ``export``, since `f2py` is looking for `f95` not `$f95`.

There's a way to modify the python-FSPS setup script to make it look for gfortran instead of f95, but ideally that wouldn't be necessary - it's strange that your numpy/f2py does not know about the available fortran compilers.

But if all else fails, you can try adding
``--f90exec=/apps/compilers/gcc/5.2.0/bin/gfortran``
to the flag strings on lines 38 and 59 of the setup.py script.

**Comment by bd-j** [comment]
alternatively, if you have sufficient permissions you could create a soft link named `f95` somewhere in your $path that points to gfortran.

**Comment by dnarayanan** [comment]
argh this was a simple work around....I can't believe it didn't occur to
me.  The soft-link was enough to get the job done which...at this
point...is all i care about :)

Thanks Ben!

-d

**Comment by bd-j** [comment]
glad it's working!
