### ISSUE TITLE
Problems in adding new filters

### ISSUE THREAD

**Issue by PBarmby** [dfm/python-fsps#65]
I've added some new filters to FSPS (see [here](https://github.com/PBarmby/fsps/commit/ad354c37791e6ee93283be45c8ea7c6ad016b303) for changes) and recompiled it, but when I try to use get_mags for the new filters, it fails like so:

```
sp = fsps.StellarPopulation(compute_vega_mags=True, add_neb_emission=True, cloudy_dust=True, sfh=0,  zmet=2)
narrow_filts = [ 'wfc3_uvis_f373n', 'wfc3_uvis_f487n','wfc3_uvis_f502n', 'wfc3_uvis_f657n', 'wfc3_uvis_f673n']
mn = sp.get_mags(bands=narrow_filts)

/Users/pauline/anaconda/lib/python2.7/site-packages/fsps-0.2.2-py2.7-macosx-10.6-x86_64.egg/fsps/fsps.pyc in get_mags(self, zmet, tage, redshift, bands)
    606         else:
    607             if bands is not None:
--> 608                 return mags[:, user_sorted_inds]
    609             else:
    610                 return mags

IndexError: index 138 is out of bounds for axis 1 with size 138
```

Seems like this might be related to #46 or #15 ?

**Comment by PBarmby** [comment]
OK, answered my own question - have to redo the `python setupy.py install` step after recompiling FSPS. Now things work. Issue closed.

**Comment by bd-j** [comment]
Glad it's sorted, thanks for closing the issue.
