### ISSUE TITLE
Metallicity out of range error

### ISSUE THREAD

**Issue by rrgupta** [dfm/python-fsps#67]
Hi,
I just installed FSPS v3.0 and python fsps v0.2.2 yesterday. I went to try the example here: 
http://dan.iel.fm/python-fsps/current/stellarpop_api/#example
but when I instatiate the SSP following the example I get the following error:
`AssertionError: zmet=20 out of range [1, 12]`
This seems odd since my understanding is the Padova isochrones are used by default and I have checked that the Padova zlegend.dat file contains 22 metallicities (so `zmet=20` as in the example should be fine). Any idea what is going wrong? Thanks!

**Comment by bd-j** [comment]
The bleeding edge development version of FSPS now has MIST as the default isochrone set, which only has 12 metallicities.  You can change that in ``fsps/src/sps_vars.f90`` if you want the old Padova isochrones. Sorry for the confusion, I'll try to update the python-FSPS documentation to reflect this change in defaults.

**Comment by rrgupta** [comment]
Thanks! And I just noticed this is also a closed issue someone else had brought up -- should have checked those first, sorry!

**Comment by bd-j** [comment]
no problem.  I'm going to reopen this as a reminder to fix the docs, and make it easier to see for anyone else.

**Comment by rrgupta** [comment]
Following up on this: I edited `fsps/src/sps_vars.f90` so that the set isochrone library block now reads:
```
#define MIST 0
!Padova models circa 2008
#define PADOVA 1
#define PARSEC 0
#define BASTI 0
#define GENEVA 0
```
 I then did a "make clean" in the src directory (as per Charlie's instructions in the Manual) and then ran a "make" again. However, running this example with `zmet=20` still gives the same error: `AssertionError: zmet=20 out of range [1, 12]`. Am I forgetting something else?

**Comment by bd-j** [comment]
You need to reinstall python-fsps after fsps is recompiled
```
cd /path/to/python-fsps/
python setup.py install
```

**Comment by rrgupta** [comment]
Hmm...What is the procedure if I installed with pip? Do I have to "pip uninstall" and then "pip install" again?

**Comment by dnarayanan** [comment]
i'm not 100% sure but try

>pip install packagename -U

and maybe it will work?  otherwise uninstall and install should work

**Comment by bd-j** [comment]
Docs are now updated to use zcontinuous=1 and logzsol in the example, instead of zmet.  Also an example of using the libraries attribute to know which isochrone and spectral library you are using.  Hopefully the zmet confusion shouldn't come up anymore, so closing.
