### ISSUE TITLE
Access to SFHSTAT?

### ISSUE THREAD

**Issue by rrgupta** [dfm/python-fsps#69]
Does python-fsps have access to the FSPS routine `SFHSTAT(pos,model,ssfr6,ssfr7,ssfr8,aveage)` which can return the SSFR averaged over 10^6, 10^7, and 10^8 yrs, and the mass-weighted average stellar age? If not, how do I compute the SSFR averaged over some interval along with the age (either mass- or light-weighted) for any generated CSP model?

**Comment by bd-j** [comment]
no, python-FSPS does not have access to that subroutine (which is extremely old and may not work correctly even with just FSPS). You'll have to compute those numbers yourself using the parameterized SFH. That's relatively straightforward using incomplete gamma functions, or see the source of SFHSTAT.

The exception is light weighted ages which require calculations within the FSPS fortran - these were dropped recently from the internal calculations but could be added back in.

**Comment by rrgupta** [comment]
I see, thanks. In the future, I think it would be great to have a python-fsps function that can compute SFR (or sSFR) averaged over any user-defined interval for any given generated model. Also having a function that gives mass- or light-weighted ages at each time step would great. Presumably lots of folks would find this useful, and then they don't have to write their own functions from scratch.

**Comment by bd-j** [comment]
I've got a function like that lying around somewhere.  I'll look into adding it somewhere in python-FSPS.

**Comment by rrgupta** [comment]
I looked at the code in $SPS_HOME/src/sfhstat.f90. I compared my formulas for mass-weighted ages and ssfr's to those in the code and I think I agree with all of them except for the ssfr formula for the delayed tau model (sfh=4). I believe SFHSTAT is missing a +1 in the prefactors in the numerator (though the +1 is in the prefactor in the denominator). Can you confirm this? You did mention that SFHSTAT is old and might not work -- is it possible there is also a bug in the ssfr calculation? Using the ssfr formula in SFHSTAT gives me `nan` almost half the time.

**Comment by bd-j** [comment]
In PR #73 I added an `sfr_avg` method for the StellarPopulation object that should basically do the SFHSTAT calculations (for `sfh=1,4`), though for any desired averaging timescale.  It requires scipy to work. Note also that setting `compute_light_ages` to `True` will now cause the stellar mass and log_lbol attributes to contain the stellar mass weighted age and bolometric luminosity weighted age.

**Comment by bd-j** [comment]
closing as solved by #73

**Comment by rrgupta** [comment]
Hi @bd-j 
I've been thinking more about the `sfr_avg` method recently and have a clarification question: Is the SFR(t) function you are integrating normalized to 1 Msun for -inf < t < +inf? If so, can I then interpret the output of `sfr_avg` as the *specific* star formation rate (i.e., the SFR per unit mass in units of yr^{-1})? I believe the answer both both these questions is yes (as it would allow one to simply scale up the sSFR by the inferred mass to get the SFR in Msun/yr), but I just wanted to make sure.

Thanks,
Ravi

**Comment by rrgupta** [comment]
I'm also wondering if there is a factor missing in the code for `sfr_avg` on L1094 of fsps.py:
```
mass = (tau_mass_frac * (1 - self.params['const'] - self.params['fburst']) +
        self.params['const'] * normalized_times / tmax +
        burst_in_past * self.params['fburst']
```
Should `(1 - self.params['const'] - self.params['fburst'])` actually be `(1 - self.params['const'] - burst_in_past * self.params['fburst'])` to be consistent with the final term on L1096? Otherwise `tau_mass_frac` is being reduced by `fburst` even if that burst has not yet occurred. I believe that if you provide a `tburst` value that is higher than the age at which you are requesting model properties (e.g., `tburst=20` is allowed) then FSPS just gives a warning that it will ignore the burst and not add it into the model.

**Comment by rrgupta** [comment]
Did you mean to say mass_formed > mass_current? (My understanding is that the mass formed is always greater than the current mass due to mass loss during evolution). So if I wanted to compute the standard definition of sSFR (= SFR/mass_current), would I then multiply the output of `sfr_avg` by `sp.formed_mass / sp.stellar_mass`?
Also, do you have any thoughts on my related post above regarding a possible missing factor of `burst_in_past`?
Thanks!

**Comment by bd-j** [comment]
Yes, I meant to say mass_formed > mass_current.  I also made another wrong statement - the normalization is by the integral of the SFR from 0 to `max(tage)` (this is also the problem in #103). Anyway there are clearly other issues with this function and since I don't have time to rewrite it carefully from the ground up with all use cases in mind, I think I am just going to remove it.  One can still obtain the instantaneous SFR from `StellarPopulation().sfr`

**Comment by rrgupta** [comment]
OK, fair enough. FWIW, I *think* that the `sfh=1` and `sfh=4` SFR vs. time functions can be integrated analytically obviating the need for gamma functions. If/when you get the time to revisit this I'd be happy to share some code I've got and chat more.

Cheers,
Ravi
