### ISSUE TITLE
sf_start not working properly for sfh=0?

### ISSUE THREAD

**Issue by rrgupta** [dfm/python-fsps#72]
Hi,
Based on the docs and the example on the homepage (http://dan.iel.fm/python-fsps/current/stellarpop_api/#example), I believe that `sf_start` should be a valid option for SSPs (`sfh=0`). However, I'm finding that for `sfh=0`, changing the value of `sf_start` has no effect on the output mags (i.e., it is not actually shifting the SSP in time), whereas for other SFHs (e.g., `sfh=1` or `sfh=4`), it seems to be working. 
Trying first with `sfh=0`:
```
>>> import fsps
>>> sdss_bands = fsps.find_filter('sdss')
>>> sp = fsps.StellarPopulation(sfh=0, zmet=8, sf_start=0.)
>>> sp.get_mags(tage=13.7, bands=sdss_bands)
array([ 8.8227116 ,  7.19149324,  6.13138256,  6.47717957,  5.86455388])
>>> sp = fsps.StellarPopulation(sfh=0, zmet=8, sf_start=6.)
>>> sp.get_mags(tage=13.7, bands=sdss_bands)
 COMPSP WARNING: sf_trunc<sf_start.... sf_trunc will be ignored.
array([ 8.8227116 ,  7.19149324,  6.13138256,  6.47717957,  5.86455388])
```
Now try the same with `sfh=1`:
```
>>> sp = fsps.StellarPopulation(sfh=1, zmet=8, sf_start=0.)
>>> sp.get_mags(tage=13.7, bands=sdss_bands)
array([ 8.70815378,  7.09042147,  6.03822671,  6.38155303,  5.77344132])
>>> sp = fsps.StellarPopulation(sfh=1, zmet=8, sf_start=6.)
>>> sp.get_mags(tage=13.7, bands=sdss_bands)
 COMPSP WARNING: sf_trunc<sf_start.... sf_trunc will be ignored.
array([ 7.88501673,  6.4355665 ,  5.51056325,  5.81249939,  5.28567069])
```

**Comment by bd-j** [comment]
Hi Ravi,

The py-fsps docs are wrong (see the docs for fsps itself) and fixing them was already on the list for the next set of python-fsps updates (which are coming soon!  I just finished with FSPS updates, doing the python bindings now).  Again thanks for the feedback!

**Comment by bd-j** [comment]
Just updated the doc pages to remove the misleading `sf_start` issue, make the metallicities example more robust, and show a few new features.  closing.

**Comment by rrgupta** [comment]
OK - thanks, Ben. Is it still true though that (for whatever reason) sfh=0 is the only SFH option that cannot be shifted in time using `sf_start`?

**Comment by bd-j** [comment]
sf_start only works for sfh=1,4,5

you can do something like sfh=0 with a shifted time by using sfh=0, fburst=1, and then just change tburst and sf_start
