### ISSUE TITLE
Installation problem - Windows 10

### ISSUE THREAD

**Issue by hhfbouvier** [dfm/python-fsps#76]
Hi there,

I'm running Windows 10 on my PC, and am having issues installing python-fsps. I need it alongside other packages such as sedpy, hdf5, etc... which I have had no issue with so far in order to run the "prospector" python package.

Unfortunately, I got an error saying "$SPS_HOME" variable was not set. I've now set an environment variable with that name. I'm now getting an error saying "    AttributeError: 'module' object has no attribute 'WEXITSTATUS'" which I've traced back to the __init__.py run_command(cmd) function. WEXITSTATUS does not exist on windows. I found the following help online but have not been able to resolve the problem!

def GetExitStatus(exit_code):
  """Returns the argument to exit(), or -1 if exit() wasn't called.

  Args:
    exit_code: the result value of os.system(command).
  """

  if os.name == 'nt':
    # On Windows, os.WEXITSTATUS() doesn't work and os.system() returns
    # the argument to exit() directly.
    return exit_code
  else:
    # On Unix, os.WEXITSTATUS() must be used to extract the exit status
    # from the result of os.system().
    if os.WIFEXITED(exit_code):
      return os.WEXITSTATUS(exit_code)
    else:
      return -1

I've tried modifying run_command() but to no avail, i printed the output: 

def run_command(cmd):
    """
    Open a child process, and return its exit status and stdout.

    """
    child = subprocess.Popen(cmd, shell=True, stderr=subprocess.PIPE,
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    out = [s.decode("utf-8").strip() for s in child.stdout]
    err = [s.decode("utf-8").strip() for s in child.stderr]
    w = child.wait()
    print(w, out, err)
    return w, out, err

This is returning "1 [] [u'The system cannot find the path specified.']" which unsurprisingly is leading to ImportError: Your FSPS version does not seem to be under git version control. FSPS is available on github at https://github.com/cconroy20/fsps and should be cloned from there.

Could you advise how best to install python-fsps? 

Thanks, 

Henri

**Comment by hhfbouvier** [comment]
perhaps there is a way to bypass this version check, I can confirm that i cloned FSPS directly through github as recommended

**Comment by dfm** [comment]
Unfortunately there is quite a bit of infrastructure around this project that assumes a *NIX system so it will probably be more of a mess than that. It would be great project to make python-fsps Windows compatible and test it on Appveyor but I'm not sure if it's high priority for any of the core contributors – I'd be happy to consult but I don't have time to do it myself!
