### ISSUE TITLE
Manipulating model spectra

### ISSUE THREAD

**Issue by rrgupta** [dfm/python-fsps#79]
Hi,
If I want to generate many FSPS models but do not wish to re-generate them every time I add new data (or new filters not built-in to FSPS), it seems like the best thing to do is output the model spectra at various age steps rather than the mags themselves. This way, I just need to generate FSPS models once, and save the spectra to file. Then later on I can in principle get whatever mags I want, assuming whatever cosmology I want by redshifting the model spectra and convolving them with my filter functions. Are there any python-fsps functions that exist (analogous to `sp.get_mags()`) that can act on the spectra themselves? It seems like all the functions act only on the fsps.StellarPopulation class object itself. For example, is it possible to do something like the following?:
```
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1,
                                sfh=0, logzsol=0.0, dust_type=2, dust2=0.2)
wave, spec = sp.get_spectrum(tage=13.7)
get_mags(wave, spec, redshift=some_redshift, bands=my_filters)
```
What's the best way to handle this kind of thing? The code is already doing this under the hood -- is there a way I can access that machinery for this purpose?

Thanks,
Ravi

**Comment by bd-j** [comment]
Hi Ravi,

Yes,  if you have non-standard filters the best plan is to save the spectra and do the filter convolutions yourself, unless you want to add the filters to FSPS itself.  py-FSPS does not have separate magnitude methods, and it would be very difficult to do for non-built-in filters. See the [sedpy](https://github.com/bd-j/sedpy) package (especially the ``observate`` module) for one way to do the projections easily with arbitrary filters.

**Comment by rrgupta** [comment]
Hi Ben,
I actually did add the new filters to FSPS and tested them a bit with python-fsps -- they seem to be working fine. I just was hoping I could then compute mags from spectra using existing python-fsps utilities, but it seems not, even with the filters now included. I will check out sedpy. Thanks!
Ravi
