### ISSUE TITLE
tiny modification needed in Example code to get the output of libraries (SP)

### ISSUE THREAD

**Issue by sndik16** [dfm/python-fsps#82]
Thank you for this awesome resource.

On my computer I had to type
">>>sp.libraries" 
without the final parenthesis
to get the output of libraries used

(in the following example:
http://dan.iel.fm/python-fsps/current/stellarpop_api/)

My computer:
laptop , OSX El Capitain, 10.11.6, I use Jupyter Notebook via Canopy, Python 2.7, FSPS 3.0

Otherwise, with parenthesis I get the following error:

TypeError: 'tuple' object is not callable

**Comment by bd-j** [comment]
Thanks! I'll put that on the list for the next updates

**Comment by bd-j** [comment]
I finally rebuilt the docs, this is now fixed.
