### ISSUE TITLE
computing nebular line emission

### ISSUE THREAD

**Issue by dnarayanan** [dfm/python-fsps#85]
Hi,

I'm having trouble getting the nebular line emission to work.  I'm running python-fsps hash 6b775a46cb1cceac145cf08f234f52e04385f001  and fsps hash ae31b2f63d865354ce944e5c22eba6e93e01e67d  (both of which I'm pretty sure support nebular line emission).

My sample script:

```
import fsps
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

sp = fsps.StellarPopulation()
wave,spec = sp.get_spectrum(tage=1.e-2)

sp2 = fsps.StellarPopulation(add_neb_emission = True,add_neb_continuum = True)
wave2,spec2 = sp.get_spectrum(tage=1.e-2)

fig = plt.figure()
ax = fig.add_subplot(111)
ax.loglog(wave,spec)
ax.loglog(wave2,spec2,label='Nebular Lines on')
ax.set_xlim([1e3,1e4])
ax.set_ylim([1.e-15,1.e-12])
plt.legend(loc=4)
```
plots the UV/optical SED for a population both with and without nebular line emission on.   But the SEDs look identical (and there's no obvious emission lines).  Is there something about the way I'm calling ```fsps.StellarPopulation``` that I should amend?

thanks so much
-desika

**Comment by bd-j** [comment]
First, it's usually not a good idea to run multiple StellarPopulation instances at the same time.  I would accomplish the above by writing
```
sp = fsps.StellarPopulation()
wave,spec = sp.get_spectrum(tage=1.e-2)
sp.params['add_neb_emission'] = True
sp.params['add_neb_continuum'] = True
wave2,spec2 = sp.get_spectrum(tage=1.e-2)
```

Second, in your version you're missing a "2" in 
```
wave2,spec2 = sp.get_spectrum(tage=1.e-2)
```

I'd also encourage you to update your fsps and python-fsps.  There were some bugs affecting nebular calculations in fsps that were fixed just a few months ago.

**Comment by dnarayanan** [comment]
also, what I think are the relevant parts of my `sps_vars.f90` file are:

```
MODULE SPS_VARS

  ! module to set up most arrays and variables

  IMPLICIT NONE
  SAVE

!-------set the spectral library------!
#define MILES 0
#define BASEL 1
! "C3K" currently under development.  do not use.
#define C3K 0

!------set the isochrone library------!
#define MIST 0
!Padova models circa 2008
#define PADOVA 1
#define PARSEC 0
#define BASTI 0
#define GENEVA 0
```

**Comment by dnarayanan** [comment]
oh yes - that fixed it...thanks!   (and thanks for catching the sp-->sp2 bug as well).   

And yes - I'll update now.
