### ISSUE TITLE
tabular SFHs return all-zero spectrum for tage > 11 Gyr

### ISSUE THREAD

**Issue by clairemackay** [dfm/python-fsps#88]
I've recently encountered an odd error that I've had no luck diagnosing while using tabulated star formation histories.
I'm implementing my stellar population object, e.g., as follows:

```
sp = fsps.StellarPopulation(zcontinuous=1,sfh=3)

ages = np.array([  1.5   ,   2.    ,   2.5   ,   3.    ,   3.5   ,   4.    ,
          4.5   ,   5.    ,   5.5   ,   6.    ,   6.5   ,   7.    ,
          7.5   ,   8.    ,   8.5   ,   9.    ,   9.5   ,  10.    ,
         10.25  ,  10.5   ,  10.75  ,  11.    ,  11.25  ,  11.5   ,
         11.5   ,  12.    ,  12.25  ,  12.9625,  13.1   ,  13.3   ,
         13.55  ,  13.6   ,  13.65  ])
sfrs =  np.array([ 0.01064388,  0.07342554,  0.10751006,  0.18667533,  0.2039429 ,
         0.21368737,  0.1746282 ,  0.20258633,  0.19230508,  0.19745376,
         0.26460015,  0.24665266,  0.20073408,  0.14193607,  0.06994355,
         0.03869486,  0.06280563,  0.02791233,  0.05690032,  0.05081849,
         0.04366849,  0.1072122 ,  0.04987017,  0.01957149,  0.0060195 ,
         0.03364958,  0.02865306,  0.01195153,  0.01377851,  0.01634589,
         0.05268542,  0.03616405,  0.08057589])

sp.set_tabular_sfh(ages, sfrs)
```

When I then go to get my spectra with
```
sp.get_spectrum()
```
tage < ~11 Gyr gives a reasonable spectrum, but anything older returns an array of all zeros. 
I don't see this behavior when I try using the example data bundled with FSPS, so it must be something in the way I am giving FSPS the age and SFR information. Any trouble shooting help would be much appreciated.

-Claire

**Comment by bd-j** [comment]
Hi Claire. I think the issue is that you have an age of 11.5 Gyr twice.  If I do the following:
```
ages[24] += 1e-5
sp.set_tabular_sfh(ages, sfrs)
w, spec = sp.get_spectrum()
```
Then I get nonzero spectra at all ages > 1.5 Gyr.

**Comment by bd-j** [comment]
We should probably put a check (and warning or error message) for monotonically increasing ages.

**Comment by clairemackay** [comment]
Ah, of course. Thank you so much for catching that. I think a warning in the code would be useful, and possibly a note in the set_tabular_sfh() method description that SFHs must be monotonic.
