### ISSUE TITLE
Remove requirement of parallel FSPS install?

### ISSUE THREAD

**Issue by eteq** [dfm/python-fsps#90]
To start with this is  a "does this seem like a good idea" question... But has there been thought given to full separating out the FSPS linking so that there is no need to have the `SPS_HOME` environment variable at runtime?

I might be missing a subtlety, but it looks to me like all the linking is already static, so there's no need to reach the *source* directory of `fsps`.  But am I right in guessing that it's still needed because `fsps` uses `SPS_HOME` internally to locate the various data files that come bundled with FSPS? If that's the case, I could imagine ways to trick the `python-fsps` build to use a copy of all that that gets built at install time... But before exploring this further (and possibly making a PR), my question is: has this been discussed and rejected, @dfm?

**Comment by bd-j** [comment]
@eteq don't know about @dfm but I for one have not given thought to this, and don't know enough about the f2py linking machinery to know whether it's a good idea.  It is true that `SPS_HOME` is used to find (numerous, large) bundled data files at setup.

**Comment by dfm** [comment]
This is finally implemented in #136! I mean not totally (re: data files), but the parallel FSPS install is no longer required for building.
