### ISSUE TITLE
f90 error on cluster with only local access

### ISSUE THREAD

**Issue by rjsmethurst** [dfm/python-fsps#92]
I’ve been using python-fsps for a year or so now and have come to the point where I want to use it to run code on my department’s supercomputer. 

The install on my machine was completely hassle free but not so much on the supercomputer:
	1) I don’t have write access, just local
	2) They have python 2.6.6 installed and an older version of numpy 1.3.0 

I managed to get Charlie’s FSPS installed and compiled fine using the gfortran compiler available on the supercomputer, but when I try to install python-fsps (either from the source or using pip) I get an error I can’t figure out:

`error: f90 not supported by GnuFCompiler needed for fsps.f90
`

A quick google tells me this is a common error (from stack exchange): 

```
By default, f2py prefers the GNU Fortran 77 compiler --fcompiler=gnu over the GNU Fortran 95 
compiler --fcompiler=gnu95. If you have both g77 and gfortran on your path, then f2py will, use 
g77, which cannot build Fortran 90 extensions.

If you would prefer for numpy to use gfortran over g77, you can pass the --fcompiler=gnu95 flag 
to setup.py when building your code

```

If I try to run `python setup.py install —user —fcompiler=gnu` on the supercomputer I get an error from setup.py:

`error: option --fcompiler not recognized
`

Do you know if I can change something in the setup.py file to take this an option instead? I tried to add it to the ‘flags’ variable: `flags = " -m _fsps -h fsps.pyf --overwrite-signature —-fcompiler=gnu95".split()` but that also triggered an error, a simple: `Unknown option '--fcompiler=gnu95’` from f2py.

Ideally, I’d update python and numpy to the latest versions but I obviously don’t have write access to the whole system. Any ideas, thoughts etc on how to solve without write access?

**Comment by bd-j** [comment]
yes, that is a very old numpy (and python)

if the administrators don't want to update it you might be able to create a [virtualenv](https://virtualenv.pypa.io/en/stable/) and install a newer numpy version yourself.

**Comment by dnarayanan** [comment]
are you able to install your own anaconda/miniconda environment and install `python-fsps` there?  i've had luck on a number of different supercomputing platforms with this approach.
