### ISSUE TITLE
Questions on get_mags

### ISSUE THREAD

**Issue by dptriani** [dfm/python-fsps#94]
Hi,
I am trying to convert the mags I get from several filters to flux in Jansky.
As I read the manual of fsps, I reverse this equation but get confused with the unit. 
![screen shot 2018-01-22 at 12 04 44 pm](https://user-images.githubusercontent.com/32476693/35208897-a3fab416-ff9e-11e7-9221-6f0a4c823c27.png)
I assume it would be solar luminosity per hertz? Then to convert to Jy I need to convert that using the luminosity distance?

**Comment by NadyaYuil** [comment]
@dptriani Why do you close your question?

**Comment by dptriani** [comment]
Hi @NadyaYuil I read somewhere else that the formula for the AB magnitude that I mention earlier is in cgs

**Comment by bd-j** [comment]
yes, the docs aren't too clear on this.  The reported magnitudes are absolute AB magnitudes for one solar mass formed.  So you can also convert to Janskys using
```
flux_jy = total_mass * 3631 * 10**(-0.4 * (m + dm))
```
where `dm` is the distance modulus and `total_mass` is the total mass formed in your object.  The formula you mentioned will give cgs units (at 10pc, for one solar mass formed)

**Comment by dptriani** [comment]
Hi @bd-j now I am getting confused again.
So I assume the total_mass in the above formula is in solar mass?
In python-fsps documentatiom it is stated that "If redshift is not 0, the units are apparent observed frame magnitude m, otherwise they are m−μ+2.5log(1+z), i.e. observed frame absolute magnitude."
Say I want to get the flux of each filter in redshift 1, is the AB mags that I get apparent or absolute magnitude?
I have been doing this and the result is confusing me because the SED and flux from the AB mags are not align.
`import fsps
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
import matplotlib
from matplotlib import rcParams

sp = fsps.StellarPopulation()
sp.params["sfh"] = 4
#sp.set_tabular_sfh(age=sfh[0], sfr=sfh[1])
	
#z=1 corresponds to tage 6Gyr and luminosity distance=6443.224Mpc
wavelength, spectrum = sp.get_spectrum(tage=6.0, peraa=True)
wavelength = wavelength * (u.AA)
spectrum = spectrum * (u.Lsun / u.AA)
	
band_list = ('sdss_u', 'sdss_g', 'sdss_r', 'sdss_i', 'sdss_z', '2mass_j', '2mass_h', '2mass_ks', 'irac_1', 'irac_2', 'irac_3', 'irac_4', 'mips_24', 'mips_70', 'pacs_100', 'pacs_160', 'spire_250', 'spire_350', 'spire_500')
mags = sp.get_mags(tage=6, bands=band_list)
flux = (10 ** (-(48.60 + mags)/2.5)) * (u.erg / (u.s * u.cm * u.cm * u.Hz))
distance = 6443.224 * u.Mpc
lum_des = (flux * 4 * np.pi * distance**2).decompose()

def SED(wavelength, spectrum, lum_des):
	wavelength_um = wavelength.to(u.micrometer)
	L = (spectrum * wavelength).decompose()
	L_sun = L.to(u.Lsun)
	lambda_eff = (3556.5, 4702.5, 6175.6, 7489.9, 8946.8, 12387.7, 16488.9, 21635.6, 35569.7, 45020.4, 57454.1, 79162.1, 235917.9, 708981.4, 1007889.7, 1618854.2, 2482638.8, 3483962.4, 5000972.5) * u.AA
	lambda_um = lambda_eff.to(u.micrometer)
	frequency = lambda_eff.to(u.Hz, equivalencies=u.spectral())
	luminosity = (lum_des * frequency).decompose()
	ABluminosity = luminosity.to(u.Lsun)
	plt.figure()
	ax = plt.subplot(111)
	plt.plot(wavelength_um, L_sun, lw=0.5, label=r'$T_{age} = 6\ Gyr$')
	plt.plot(lambda_um, ABluminosity, marker='o', lw=0.5, c='r', label='Luminosity from ABmags fsps') 
	plt.xscale('log', nonposy='clip')
	plt.yscale('log', nonposy='clip')
	plt.xlim(0.01, 10000)
	#plt.ylim(0., 0.012)
	plt.xlabel(r'$\lambda\ (\mathrm{\mu m}) $')
	plt.ylabel(r'$\lambda L_{\lambda} (L_{\odot})$')
	leg = plt.legend(loc=0, numpoints=1, labelspacing=0.1)
	leg.draw_frame(False)
	for t in leg.get_texts():
		t.set_fontsize('medium')
	plt.savefig('SED_tage6.png')
	plt.close
SED(wavelength, spectrum, lum_des)
`

**Comment by bd-j** [comment]
Hi @dptriani 

The spectrum returned by `get_spectrum()` is always restframe Lsun/Hz.   It is only the magnitudes that are apparent if `redshift` > 0 when calling `get_mags()`

It looks like you are not actually setting the `redshift` parameter in your code, so the magnitudes are AB absolute.  But you then *multiply* the corresponding flux (at 10pc) by `4*pi*distance**2`  In fact you'd want to multiply the fluxes by (10pc/distance)**2.  And this still would not take into account the redshifting of the bandpasses.  It's better to supply the redshift argument to `get_mags()`

When using tabular SFH you do not need to multiply by the total mass - that's only necessary for sfh=0, 1, 4, or 5.

**Comment by bd-j** [comment]
actually I just noticed you have set `peraa=True` in `get_spectrum`.  That means the returned spectra are restframe Lsun/AA

**Comment by bd-j** [comment]
sorry to get restframe photometric luminosities in your code you'd want to multiply flux by `4* pi * (10 * u.parsec)**2`, not `(10 * u.parsec/distance)**2` as I wrote above.
