### ISSUE TITLE
nebular emission

### ISSUE THREAD

**Issue by dptriani** [dfm/python-fsps#99]
Hi,
I want to get the spectra with nebular emission but it seems that the nebular emission line changes with tage. So I run a test here that verified that.
Alright, so I have the star formation history from simulation here and I want to get the final spectra from it including dust and nebular emission.
[sfh_MWlike_sf.txt](https://github.com/dfm/python-fsps/files/2011768/sfh_MWlike_sf.txt)
But the emission line won't appear in the final spectra (age 13.7 is the one that covers all the star formation history, right?). I am just confused why those lines appear on age 1 Gyr but not in 13.7 Gyr while the spectra in 13.7 Gyr should also include the 1 Gyr spectra.

`import fsps
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

sfh_q = np.loadtxt('sfh_MWlike_sf.txt', delimiter='\t')
sfh = sfh_q.T

sp = fsps.StellarPopulation()
sp.params["sfh"] = 3
sp.set_tabular_sfh(age=sfh[0], sfr=sfh[1])
sp.params["imf_type"]=0
sp.params["dust_type"]=2
sp.params['cloudy_dust'] = True
sp.params['add_dust_emission'] = True
sp.params['dust1']=0.0
sp.params['dust2']=0.3
sp.params['duste_qpah'] = 2.5
#sp.params['duste_umin'] = 10
sp.params['add_neb_emission'] = 1
sp.params['gas_logu'] = -2
sp.params['gas_logz'] = -1.7

esp = fsps.StellarPopulation()
esp.params["sfh"] = 3
esp.set_tabular_sfh(age=sfh[0], sfr=sfh[1])
esp.params["imf_type"]=0
esp.params["dust_type"]=2
esp.params['cloudy_dust'] = True
esp.params['add_dust_emission'] = True
sp.params['dust1']=0.0
esp.params['dust2']=0.3
esp.params['duste_qpah'] = 2.5
#sp.params['duste_umin'] = 10
esp.params['add_neb_emission'] = 0

age = 1. #(in units of Gyr)
lam, spec = sp.get_spectrum(peraa=True, tage=age) 
lam, espec = esp.get_spectrum(peraa=True, tage=age)

age1 = 13.7 #(in units of Gyr)
lam1, spec1 = sp.get_spectrum(peraa=True, tage=age1) 
lam1, espec1 = esp.get_spectrum(peraa=True, tage=age1)

residual = espec1-spec1 / spec1

# Plot the SFR
fig, ax = plt.subplots(1, figsize=(8,8))
ax.loglog(lam, spec, label='Nebular Model, 1Gyr')
ax.loglog(lam, espec, ':', label='No Nebular Model, 1Gyr')
ax.loglog(lam1, spec1, label='Nebular Model, 13.7Gyr')
ax.loglog(lam1, espec1, ':', label='No Nebular Model, 13.7Gyr')
ax.legend(loc=0, frameon=False)
ax.set_ylim(1e2, 1e8)
ax.set_xlabel(r'$\log[\;\mathrm{Wavelength}\,(\mathrm{\AA})\;]$', size=12)
ax.set_ylabel(r'log L$_{\odot}/\mathrm{\AA}$', size=12)
plt.show()
`

**Comment by bd-j** [comment]
In your SFH, the SFR goes to zero at 13.6098 Gyr, so when you ask for the spectrum at tage=13.7 Gyr, the SFR has been zero for almost 0.1 Gyr.  Therefore there are no young stars to produce the nebular emission.  It is true that the stars that were in the spectrum at t=1 Gyr are in the spectrum at t=13.7 Gyr, but they are now >12.7 Gyr old, and so do not produce ionizing flux anymore (whereas, for t=1Gyr, the SFR has 'recent'y' been greater than zero, and so there are young stars that can produce ionizing flux and hence nebular emission.)  Hope this helps.

**Comment by dptriani** [comment]
I see, but when I changed the second age to be 13 Gyr (with SFR more or less similar to 1 Gyr), I still get almost no nebular lines.

**Comment by bd-j** [comment]
Assuming this is resolved and closing.
